In [1]:
import chromatin_algos
import evaluator

In [3]:
result = evaluator.evaluate(dataframe = chromatin_algos.algo5d(1))

HEAD
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0
BINS  IntervalIndex([(10000017, 10000017], (10000017, 10000117],
               (10000117, 10000217], (10000217, 10000317],
               (10000317, 10000417], (10000417, 10000517],
               (10000517, 10000617], (10000617, 10000717],
               (10000717, 10000817], (10000817, 10000917],
               ...
               (25556017, 25556117], (25556117, 25556217],
               (25556217, 25556317], (25556317, 25556417],
               (25556417, 25556517], (25556517, 25556617],
               (25556617, 25556717], (25556717, 25556817],
               (25556817, 25556917], (25556917, 25556940]],
              dtype='interval[int64, right]', length=155571)
HEAD w BINS
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0

           bin_offset_0
0  (10000017, 10000117]
1  (10000017, 10000117]
2  (10000117, 10000217]
3  (10000217, 10000317]
4  (10000217, 10000317]
TAIL w BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  25556879  25556879  18_25556879    1.0    9.0    3.0
699996       18  25556894  25556894  18_25556894    1.0   14.0    1.0
699997       18  25556919  25556919  18_25556919    0.0    0.0    0.0
699998       18  25556927  25556927  18_25556927    0.0    3.0    2.0
699999       18  25556940  25556940  18_25556940    7.0    5.0    7.0

                bin_offset_0
699995  (25556817, 25556917]
699996  (25556817, 25556917]
699997  (25556917, 25556940]
699998  (25556917, 25556940]
699999  (25556917, 25556940]

/Users/lukas/VU/bio-baigiamasis/chromatin_algos.py:150: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0     10000017
1     0.0     10000017
2     0.0     10000117
3     0.0     10000217
4    14.0     10000317
5     3.0     10000417
6     3.0     10000517
7     0.0     10000617
8    16.0     10000717
9     2.0     10000817
10    0.0     10000917
11    0.0     10001017
12    1.0     10001117
13    1.0     10001217
14    0.0     10001317
15    4.0     10001417
16    3.0     10001517
17    0.0     10001617
18    0.0     10001717
19    1.0     10001817
20    0.0     10001917
21    6.0     10002017
22   21.0     10002117
23   14.0     10002217
24    1.0     10002317
25    0.0     10002417
26    0.0     10002517
27    2.0     10002617
28   12.0     10002717
29    9.0     10002817
30    0.0     10002917
31    1.0     10003017
32    0.0     10003117
33    7.0     10003217
34    0.0     10003317
35    4.0     10003417
36    1.0     10003517
37    0.0     10003617
38    0.0     10003717
39    1.0     10003817
40    4.0     10003917
41    1.0     10004017
42    4.0     10004117
43    1.0     10004217
44    2.0     10004317
45    7.0     10004417
46   29.0     10004517
47    1.0     10004617
48   12.0     10004717
49    8.0     10004817
(155571, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 155571
ranges ilgis: 155571
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         0.0      0            0      0     0
2         0.0      0            0      0     0
3         0.0      0            0      0     0
4        14.0      0            0      0     0
...       ...    ...          ...    ...   ...
155566   17.0      0            0      0     0
155567    5.0      0            0      0     0
155568   12.0      0            0      0     0
155569    8.0      0            0      0     0
155570    7.0      0            0      0     0

[155571 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         0.0             0                   0             0            0
2         0.0             0                   0             0            0
3         0.0             0                   0             0            0
4        14.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
155566   17.0             0                   0             0            0
155567    5.0             0                   0             0            0
155568   12.0             0                   0             0            0
155569    8.0             0                   0             0            0
155570    7.0             0                   0             0            0

[155571 rows x 5 columns]
0.10966696877952832
[0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0
 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0
 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1
 0 0 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1
 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]

In [4]:
print(result)

count                  11670.000000
mean                     146.195373
std                      109.606325
min                      100.000000
25%                      100.000000
50%                      100.000000
75%                      200.000000
max                     1600.000000
ATACseq_overlap            0.564254
DNAseq_overlap             0.486887
genes_overlap              0.650512
percentage_open            0.066757
percentage_open_adj        0.109668
Name: Length, dtype: float64

In [5]:
import pandas as pd

for i in range(6):
    scale = 2 ** i
    print("Runnning scale", scale)
    evaluation = evaluator.evaluate(dataframe = chromatin_algos.algo5d(scale))
    result = pd.concat([result, evaluation], axis=1)

Runnning scale 1
HEAD
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0
BINS  IntervalIndex([(10000017, 10000017], (10000017, 10000117],
               (10000117, 10000217], (10000217, 10000317],
               (10000317, 10000417], (10000417, 10000517],
               (10000517, 10000617], (10000617, 10000717],
               (10000717, 10000817], (10000817, 10000917],
               ...
               (25556017, 25556117], (25556117, 25556217],
               (25556217, 25556317], (25556317, 25556417],
               (25556417, 25556517], (25556517, 25556617],
               (25556617, 25556717], (25556717, 25556817],
               (25556817, 25556917], (25556917, 25556940]],
              dtype='interval[int64, right]', length=155571)
HEAD w BINS
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0

           bin_offset_0
0  (10000017, 10000117]
1  (10000017, 10000117]
2  (10000117, 10000217]
3  (10000217, 10000317]
4  (10000217, 10000317]
TAIL w BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  25556879  25556879  18_25556879    1.0    9.0    3.0
699996       18  25556894  25556894  18_25556894    1.0   14.0    1.0
699997       18  25556919  25556919  18_25556919    0.0    0.0    0.0
699998       18  25556927  25556927  18_25556927    0.0    3.0    2.0
699999       18  25556940  25556940  18_25556940    7.0    5.0    7.0

                bin_offset_0
699995  (25556817, 25556917]
699996  (25556817, 25556917]
699997  (25556917, 25556940]
699998  (25556917, 25556940]
699999  (25556917, 25556940]

/Users/lukas/VU/bio-baigiamasis/chromatin_algos.py:150: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0     10000017
1     0.0     10000017
2     0.0     10000117
3     0.0     10000217
4    14.0     10000317
5     3.0     10000417
6     3.0     10000517
7     0.0     10000617
8    16.0     10000717
9     2.0     10000817
10    0.0     10000917
11    0.0     10001017
12    1.0     10001117
13    1.0     10001217
14    0.0     10001317
15    4.0     10001417
16    3.0     10001517
17    0.0     10001617
18    0.0     10001717
19    1.0     10001817
20    0.0     10001917
21    6.0     10002017
22   21.0     10002117
23   14.0     10002217
24    1.0     10002317
25    0.0     10002417
26    0.0     10002517
27    2.0     10002617
28   12.0     10002717
29    9.0     10002817
30    0.0     10002917
31    1.0     10003017
32    0.0     10003117
33    7.0     10003217
34    0.0     10003317
35    4.0     10003417
36    1.0     10003517
37    0.0     10003617
38    0.0     10003717
39    1.0     10003817
40    4.0     10003917
41    1.0     10004017
42    4.0     10004117
43    1.0     10004217
44    2.0     10004317
45    7.0     10004417
46   29.0     10004517
47    1.0     10004617
48   12.0     10004717
49    8.0     10004817
(155571, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 155571
ranges ilgis: 155571
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         0.0      0            0      0     0
2         0.0      0            0      0     0
3         0.0      0            0      0     0
4        14.0      0            0      0     0
...       ...    ...          ...    ...   ...
155566   17.0      0            0      0     0
155567    5.0      0            0      0     0
155568   12.0      0            0      0     0
155569    8.0      0            0      0     0
155570    7.0      0            0      0     0

[155571 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         0.0             0                   0             0            0
2         0.0             0                   0             0            0
3         0.0             0                   0             0            0
4        14.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
155566   17.0             0                   0             0            0
155567    5.0             0                   0             0            0
155568   12.0             0                   0             0            0
155569    8.0             0                   0             0            0
155570    7.0             0                   0             0            0

[155571 rows x 5 columns]
0.13064131489802083
[0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0
 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0
 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1
 0 0 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1
 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 2
HEAD
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0
BINS  IntervalIndex([(10000017, 10000017], (10000017, 10000117],
               (10000117, 10000217], (10000217, 10000317],
               (10000317, 10000417], (10000417, 10000517],
               (10000517, 10000617], (10000617, 10000717],
               (10000717, 10000817], (10000817, 10000917],
               ...
               (25556017, 25556117], (25556117, 25556217],
               (25556217, 25556317], (25556317, 25556417],
               (25556417, 25556517], (25556517, 25556617],
               (25556617, 25556717], (25556717, 25556817],
               (25556817, 25556917], (25556917, 25556940]],
              dtype='interval[int64, right]', length=155571)
HEAD w BINS
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0

           bin_offset_0
0  (10000017, 10000117]
1  (10000017, 10000117]
2  (10000117, 10000217]
3  (10000217, 10000317]
4  (10000217, 10000317]
TAIL w BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  25556879  25556879  18_25556879    1.0    9.0    3.0
699996       18  25556894  25556894  18_25556894    1.0   14.0    1.0
699997       18  25556919  25556919  18_25556919    0.0    0.0    0.0
699998       18  25556927  25556927  18_25556927    0.0    3.0    2.0
699999       18  25556940  25556940  18_25556940    7.0    5.0    7.0

                bin_offset_0
699995  (25556817, 25556917]
699996  (25556817, 25556917]
699997  (25556917, 25556940]
699998  (25556917, 25556940]
699999  (25556917, 25556940]

/Users/lukas/VU/bio-baigiamasis/chromatin_algos.py:150: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0     10000017
1     0.0     10000017
2     0.0     10000117
3     0.0     10000217
4    14.0     10000317
5     3.0     10000417
6     3.0     10000517
7     0.0     10000617
8    16.0     10000717
9     2.0     10000817
10    0.0     10000917
11    0.0     10001017
12    1.0     10001117
13    1.0     10001217
14    0.0     10001317
15    4.0     10001417
16    3.0     10001517
17    0.0     10001617
18    0.0     10001717
19    1.0     10001817
20    0.0     10001917
21    6.0     10002017
22   21.0     10002117
23   14.0     10002217
24    1.0     10002317
25    0.0     10002417
26    0.0     10002517
27    2.0     10002617
28   12.0     10002717
29    9.0     10002817
30    0.0     10002917
31    1.0     10003017
32    0.0     10003117
33    7.0     10003217
34    0.0     10003317
35    4.0     10003417
36    1.0     10003517
37    0.0     10003617
38    0.0     10003717
39    1.0     10003817
40    4.0     10003917
41    1.0     10004017
42    4.0     10004117
43    1.0     10004217
44    2.0     10004317
45    7.0     10004417
46   29.0     10004517
47    1.0     10004617
48   12.0     10004717
49    8.0     10004817
(155571, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 155571
ranges ilgis: 155571
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         0.0      0            0      0     0
2         0.0      0            0      0     0
3         0.0      0            0      0     0
4        14.0      0            0      0     0
...       ...    ...          ...    ...   ...
155566   17.0      0            0      0     0
155567    5.0      0            0      0     0
155568   12.0      0            0      0     0
155569    8.0      0            0      0     0
155570    7.0      0            0      0     0

[155571 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         0.0             0                   0             0            0
2         0.0             0                   0             0            0
3         0.0             0                   0             0            0
4        14.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
155566   17.0             0                   0             0            0
155567    5.0             0                   0             0            0
155568   12.0             0                   0             0            0
155569    8.0             0                   0             0            0
155570    7.0             0                   0             0            0

[155571 rows x 5 columns]
0.8693586851019791
[1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1
 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1
 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1
 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1
 0 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0
 1 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 0
 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1]
Runnning scale 4
HEAD
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0
BINS  IntervalIndex([(10000017, 10000017], (10000017, 10000117],
               (10000117, 10000217], (10000217, 10000317],
               (10000317, 10000417], (10000417, 10000517],
               (10000517, 10000617], (10000617, 10000717],
               (10000717, 10000817], (10000817, 10000917],
               ...
               (25556017, 25556117], (25556117, 25556217],
               (25556217, 25556317], (25556317, 25556417],
               (25556417, 25556517], (25556517, 25556617],
               (25556617, 25556717], (25556717, 25556817],
               (25556817, 25556917], (25556917, 25556940]],
              dtype='interval[int64, right]', length=155571)
HEAD w BINS
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0

           bin_offset_0
0  (10000017, 10000117]
1  (10000017, 10000117]
2  (10000117, 10000217]
3  (10000217, 10000317]
4  (10000217, 10000317]
TAIL w BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  25556879  25556879  18_25556879    1.0    9.0    3.0
699996       18  25556894  25556894  18_25556894    1.0   14.0    1.0
699997       18  25556919  25556919  18_25556919    0.0    0.0    0.0
699998       18  25556927  25556927  18_25556927    0.0    3.0    2.0
699999       18  25556940  25556940  18_25556940    7.0    5.0    7.0

                bin_offset_0
699995  (25556817, 25556917]
699996  (25556817, 25556917]
699997  (25556917, 25556940]
699998  (25556917, 25556940]
699999  (25556917, 25556940]

/Users/lukas/VU/bio-baigiamasis/chromatin_algos.py:150: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0     10000017
1     0.0     10000017
2     0.0     10000117
3     0.0     10000217
4    14.0     10000317
5     3.0     10000417
6     3.0     10000517
7     0.0     10000617
8    16.0     10000717
9     2.0     10000817
10    0.0     10000917
11    0.0     10001017
12    1.0     10001117
13    1.0     10001217
14    0.0     10001317
15    4.0     10001417
16    3.0     10001517
17    0.0     10001617
18    0.0     10001717
19    1.0     10001817
20    0.0     10001917
21    6.0     10002017
22   21.0     10002117
23   14.0     10002217
24    1.0     10002317
25    0.0     10002417
26    0.0     10002517
27    2.0     10002617
28   12.0     10002717
29    9.0     10002817
30    0.0     10002917
31    1.0     10003017
32    0.0     10003117
33    7.0     10003217
34    0.0     10003317
35    4.0     10003417
36    1.0     10003517
37    0.0     10003617
38    0.0     10003717
39    1.0     10003817
40    4.0     10003917
41    1.0     10004017
42    4.0     10004117
43    1.0     10004217
44    2.0     10004317
45    7.0     10004417
46   29.0     10004517
47    1.0     10004617
48   12.0     10004717
49    8.0     10004817
(155571, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 155571
ranges ilgis: 155571
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         0.0      0            0      0     0
2         0.0      0            0      0     0
3         0.0      0            0      0     0
4        14.0      0            0      0     0
...       ...    ...          ...    ...   ...
155566   17.0      0            0      0     0
155567    5.0      0            0      0     0
155568   12.0      0            0      0     0
155569    8.0      0            0      0     0
155570    7.0      0            0      0     0

[155571 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         0.0             0                   0             0            0
2         0.0             0                   0             0            0
3         0.0             0                   0             0            0
4        14.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
155566   17.0             0                   0             0            0
155567    5.0             0                   0             0            0
155568   12.0             0                   0             0            0
155569    8.0             0                   0             0            0
155570    7.0             0                   0             0            0

[155571 rows x 5 columns]
0.13064131489802083
[0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0
 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0
 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1
 0 0 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1
 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 8
HEAD
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0
BINS  IntervalIndex([(10000017, 10000017], (10000017, 10000117],
               (10000117, 10000217], (10000217, 10000317],
               (10000317, 10000417], (10000417, 10000517],
               (10000517, 10000617], (10000617, 10000717],
               (10000717, 10000817], (10000817, 10000917],
               ...
               (25556017, 25556117], (25556117, 25556217],
               (25556217, 25556317], (25556317, 25556417],
               (25556417, 25556517], (25556517, 25556617],
               (25556617, 25556717], (25556717, 25556817],
               (25556817, 25556917], (25556917, 25556940]],
              dtype='interval[int64, right]', length=155571)
HEAD w BINS
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0

           bin_offset_0
0  (10000017, 10000117]
1  (10000017, 10000117]
2  (10000117, 10000217]
3  (10000217, 10000317]
4  (10000217, 10000317]
TAIL w BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  25556879  25556879  18_25556879    1.0    9.0    3.0
699996       18  25556894  25556894  18_25556894    1.0   14.0    1.0
699997       18  25556919  25556919  18_25556919    0.0    0.0    0.0
699998       18  25556927  25556927  18_25556927    0.0    3.0    2.0
699999       18  25556940  25556940  18_25556940    7.0    5.0    7.0

                bin_offset_0
699995  (25556817, 25556917]
699996  (25556817, 25556917]
699997  (25556917, 25556940]
699998  (25556917, 25556940]
699999  (25556917, 25556940]

/Users/lukas/VU/bio-baigiamasis/chromatin_algos.py:150: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0     10000017
1     0.0     10000017
2     0.0     10000117
3     0.0     10000217
4    14.0     10000317
5     3.0     10000417
6     3.0     10000517
7     0.0     10000617
8    16.0     10000717
9     2.0     10000817
10    0.0     10000917
11    0.0     10001017
12    1.0     10001117
13    1.0     10001217
14    0.0     10001317
15    4.0     10001417
16    3.0     10001517
17    0.0     10001617
18    0.0     10001717
19    1.0     10001817
20    0.0     10001917
21    6.0     10002017
22   21.0     10002117
23   14.0     10002217
24    1.0     10002317
25    0.0     10002417
26    0.0     10002517
27    2.0     10002617
28   12.0     10002717
29    9.0     10002817
30    0.0     10002917
31    1.0     10003017
32    0.0     10003117
33    7.0     10003217
34    0.0     10003317
35    4.0     10003417
36    1.0     10003517
37    0.0     10003617
38    0.0     10003717
39    1.0     10003817
40    4.0     10003917
41    1.0     10004017
42    4.0     10004117
43    1.0     10004217
44    2.0     10004317
45    7.0     10004417
46   29.0     10004517
47    1.0     10004617
48   12.0     10004717
49    8.0     10004817
(155571, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 155571
ranges ilgis: 155571
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         0.0      0            0      0     0
2         0.0      0            0      0     0
3         0.0      0            0      0     0
4        14.0      0            0      0     0
...       ...    ...          ...    ...   ...
155566   17.0      0            0      0     0
155567    5.0      0            0      0     0
155568   12.0      0            0      0     0
155569    8.0      0            0      0     0
155570    7.0      0            0      0     0

[155571 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         0.0             0                   0             0            0
2         0.0             0                   0             0            0
3         0.0             0                   0             0            0
4        14.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
155566   17.0             0                   0             0            0
155567    5.0             0                   0             0            0
155568   12.0             0                   0             0            0
155569    8.0             0                   0             0            0
155570    7.0             0                   0             0            0

[155571 rows x 5 columns]
0.10966696877952832
[0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0
 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0
 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1
 0 0 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1
 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 16
HEAD
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0
BINS  IntervalIndex([(10000017, 10000017], (10000017, 10000117],
               (10000117, 10000217], (10000217, 10000317],
               (10000317, 10000417], (10000417, 10000517],
               (10000517, 10000617], (10000617, 10000717],
               (10000717, 10000817], (10000817, 10000917],
               ...
               (25556017, 25556117], (25556117, 25556217],
               (25556217, 25556317], (25556317, 25556417],
               (25556417, 25556517], (25556517, 25556617],
               (25556617, 25556717], (25556717, 25556817],
               (25556817, 25556917], (25556917, 25556940]],
              dtype='interval[int64, right]', length=155571)
HEAD w BINS
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0

           bin_offset_0
0  (10000017, 10000117]
1  (10000017, 10000117]
2  (10000117, 10000217]
3  (10000217, 10000317]
4  (10000217, 10000317]
TAIL w BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  25556879  25556879  18_25556879    1.0    9.0    3.0
699996       18  25556894  25556894  18_25556894    1.0   14.0    1.0
699997       18  25556919  25556919  18_25556919    0.0    0.0    0.0
699998       18  25556927  25556927  18_25556927    0.0    3.0    2.0
699999       18  25556940  25556940  18_25556940    7.0    5.0    7.0

                bin_offset_0
699995  (25556817, 25556917]
699996  (25556817, 25556917]
699997  (25556917, 25556940]
699998  (25556917, 25556940]
699999  (25556917, 25556940]

/Users/lukas/VU/bio-baigiamasis/chromatin_algos.py:150: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0     10000017
1     0.0     10000017
2     0.0     10000117
3     0.0     10000217
4    14.0     10000317
5     3.0     10000417
6     3.0     10000517
7     0.0     10000617
8    16.0     10000717
9     2.0     10000817
10    0.0     10000917
11    0.0     10001017
12    1.0     10001117
13    1.0     10001217
14    0.0     10001317
15    4.0     10001417
16    3.0     10001517
17    0.0     10001617
18    0.0     10001717
19    1.0     10001817
20    0.0     10001917
21    6.0     10002017
22   21.0     10002117
23   14.0     10002217
24    1.0     10002317
25    0.0     10002417
26    0.0     10002517
27    2.0     10002617
28   12.0     10002717
29    9.0     10002817
30    0.0     10002917
31    1.0     10003017
32    0.0     10003117
33    7.0     10003217
34    0.0     10003317
35    4.0     10003417
36    1.0     10003517
37    0.0     10003617
38    0.0     10003717
39    1.0     10003817
40    4.0     10003917
41    1.0     10004017
42    4.0     10004117
43    1.0     10004217
44    2.0     10004317
45    7.0     10004417
46   29.0     10004517
47    1.0     10004617
48   12.0     10004717
49    8.0     10004817
(155571, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 155571
ranges ilgis: 155571
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         0.0      0            0      0     0
2         0.0      0            0      0     0
3         0.0      0            0      0     0
4        14.0      0            0      0     0
...       ...    ...          ...    ...   ...
155566   17.0      0            0      0     0
155567    5.0      0            0      0     0
155568   12.0      0            0      0     0
155569    8.0      0            0      0     0
155570    7.0      0            0      0     0

[155571 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         0.0             0                   0             0            0
2         0.0             0                   0             0            0
3         0.0             0                   0             0            0
4        14.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
155566   17.0             0                   0             0            0
155567    5.0             0                   0             0            0
155568   12.0             0                   0             0            0
155569    8.0             0                   0             0            0
155570    7.0             0                   0             0            0

[155571 rows x 5 columns]
0.8693586851019791
[1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1
 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1
 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1
 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1
 0 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0
 1 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 0
 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1]
Runnning scale 32
HEAD
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0
BINS  IntervalIndex([(10000017, 10000017], (10000017, 10000117],
               (10000117, 10000217], (10000217, 10000317],
               (10000317, 10000417], (10000417, 10000517],
               (10000517, 10000617], (10000617, 10000717],
               (10000717, 10000817], (10000817, 10000917],
               ...
               (25556017, 25556117], (25556117, 25556217],
               (25556217, 25556317], (25556317, 25556417],
               (25556417, 25556517], (25556517, 25556617],
               (25556617, 25556717], (25556717, 25556817],
               (25556817, 25556917], (25556917, 25556940]],
              dtype='interval[int64, right]', length=155571)
HEAD w BINS
  seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  10000018  10000018  18_10000018    0.0    0.0    0.0
1       18  10000117  10000117  18_10000117    0.0    0.0    0.0
2       18  10000155  10000155  18_10000155    0.0    0.0    1.0
3       18  10000222  10000222  18_10000222    0.0    4.0    0.0
4       18  10000281  10000281  18_10000281    0.0    0.0    0.0

           bin_offset_0
0  (10000017, 10000117]
1  (10000017, 10000117]
2  (10000117, 10000217]
3  (10000217, 10000317]
4  (10000217, 10000317]
TAIL w BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  25556879  25556879  18_25556879    1.0    9.0    3.0
699996       18  25556894  25556894  18_25556894    1.0   14.0    1.0
699997       18  25556919  25556919  18_25556919    0.0    0.0    0.0
699998       18  25556927  25556927  18_25556927    0.0    3.0    2.0
699999       18  25556940  25556940  18_25556940    7.0    5.0    7.0

                bin_offset_0
699995  (25556817, 25556917]
699996  (25556817, 25556917]
699997  (25556917, 25556940]
699998  (25556917, 25556940]
699999  (25556917, 25556940]

/Users/lukas/VU/bio-baigiamasis/chromatin_algos.py:150: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0     10000017
1     0.0     10000017
2     0.0     10000117
3     0.0     10000217
4    14.0     10000317
5     3.0     10000417
6     3.0     10000517
7     0.0     10000617
8    16.0     10000717
9     2.0     10000817
10    0.0     10000917
11    0.0     10001017
12    1.0     10001117
13    1.0     10001217
14    0.0     10001317
15    4.0     10001417
16    3.0     10001517
17    0.0     10001617
18    0.0     10001717
19    1.0     10001817
20    0.0     10001917
21    6.0     10002017
22   21.0     10002117
23   14.0     10002217
24    1.0     10002317
25    0.0     10002417
26    0.0     10002517
27    2.0     10002617
28   12.0     10002717
29    9.0     10002817
30    0.0     10002917
31    1.0     10003017
32    0.0     10003117
33    7.0     10003217
34    0.0     10003317
35    4.0     10003417
36    1.0     10003517
37    0.0     10003617
38    0.0     10003717
39    1.0     10003817
40    4.0     10003917
41    1.0     10004017
42    4.0     10004117
43    1.0     10004217
44    2.0     10004317
45    7.0     10004417
46   29.0     10004517
47    1.0     10004617
48   12.0     10004717
49    8.0     10004817
(155571, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 155571
ranges ilgis: 155571
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         0.0      0            0      0     0
2         0.0      0            0      0     0
3         0.0      0            0      0     0
4        14.0      0            0      0     0
...       ...    ...          ...    ...   ...
155566   17.0      0            0      0     0
155567    5.0      0            0      0     0
155568   12.0      0            0      0     0
155569    8.0      0            0      0     0
155570    7.0      0            0      0     0

[155571 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         0.0             0                   0             0            0
2         0.0             0                   0             0            0
3         0.0             0                   0             0            0
4        14.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
155566   17.0             0                   0             0            0
155567    5.0             0                   0             0            0
155568   12.0             0                   0             0            0
155569    8.0             0                   0             0            0
155570    7.0             0                   0             0            0

[155571 rows x 5 columns]
0.8693586851019791
[1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1
 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1
 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1
 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1
 0 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0
 1 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 0
 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1]

In [6]:
print(result)

                           Length        Length        Length        Length  \
count                11670.000000  13484.000000  13484.000000  13484.000000
mean                   146.195373    150.726787    150.726787    150.726787
std                    109.606325    116.833191    116.833191    116.833191
min                    100.000000    100.000000    100.000000    100.000000
25%                    100.000000    100.000000    100.000000    100.000000
50%                    100.000000    100.000000    100.000000    100.000000
75%                    200.000000    200.000000    200.000000    200.000000
max                   1600.000000   1800.000000   1800.000000   1800.000000
ATACseq_overlap          0.564254      0.583832      0.583832      0.583832
DNAseq_overlap           0.486887      0.510847      0.510847      0.510847
genes_overlap            0.650512      0.648027      0.648027      0.648027
percentage_open          0.066757      0.079524      0.079524      0.079524
percentage_open_adj      0.109668      0.130643      0.130643      0.130643

                           Length        Length        Length
count                11670.000000  13484.000000  13484.000000
mean                   146.195373    150.726787    150.726787
std                    109.606325    116.833191    116.833191
min                    100.000000    100.000000    100.000000
25%                    100.000000    100.000000    100.000000
50%                    100.000000    100.000000    100.000000
75%                    200.000000    200.000000    200.000000
max                   1600.000000   1800.000000   1800.000000
ATACseq_overlap          0.564254      0.583832      0.583832
DNAseq_overlap           0.486887      0.510847      0.510847
genes_overlap            0.650512      0.648027      0.648027
percentage_open          0.066757      0.079524      0.079524
percentage_open_adj      0.109668      0.130643      0.130643