In [1]:
import chromatin_algos
import evaluator
import generate_consensus

In [4]:
result = evaluator.evaluate(merged_ranges = chromatin_algos.algo5d_aggregated(16, 10, 3), model_name="test run")

HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000018],   (3000018, 3000118],
                 (3000118, 3000218],   (3000218, 3000318],
                 (3000318, 3000418],   (3000418, 3000518],
                 (3000518, 3000618],   (3000618, 3000718],
                 (3000718, 3000818],   (3000818, 3000918],
               ...
               (18260718, 18260818], (18260818, 18260918],
               (18260918, 18261018], (18261018, 18261118],
               (18261118, 18261218], (18261218, 18261318],
               (18261318, 18261418], (18261418, 18261518],
               (18261518, 18261618], (18261618, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

         bin_offset_0  target_count
0  (3000018, 3000118]             1
1  (3000018, 3000118]             1
2  (3000018, 3000118]             1
3  (3000018, 3000118]             1
4  (3000018, 3000118]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

                bin_offset_0  target_count
699995  (18261518, 18261618]             1
699996  (18261518, 18261618]             1
699997  (18261618, 18261710]             1
699998  (18261618, 18261710]             1
699999  (18261618, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
          bin_offset_0  TT_S0  target_count  starting_nt
0   (3000018, 3000018]    0.0             0      3000018
1   (3000018, 3000118]    7.0            11      3000018
2   (3000118, 3000218]    1.0             4      3000118
3   (3000218, 3000318]    2.0             4      3000218
4   (3000318, 3000418]    0.0             4      3000318
5   (3000418, 3000518]    0.0             2      3000418
6   (3000518, 3000618]    0.0             2      3000518
7   (3000618, 3000718]    0.0             4      3000618
8   (3000718, 3000818]    0.0             7      3000718
9   (3000818, 3000918]    0.0             3      3000818
10  (3000918, 3001018]    0.0             3      3000918
11  (3001018, 3001118]    2.0             6      3001018
12  (3001118, 3001218]    0.0             2      3001118
13  (3001218, 3001318]    0.0             4      3001218
14  (3001318, 3001418]    0.0             3      3001318
15  (3001418, 3001518]    1.0             4      3001418
16  (3001518, 3001618]    3.0            10      3001518
17  (3001618, 3001718]    3.0             7      3001618
18  (3001718, 3001818]    0.0             6      3001718
19  (3001818, 3001918]    0.0             2      3001818
20  (3001918, 3002018]    1.0             3      3001918
21  (3002018, 3002118]    0.0             2      3002018
22  (3002118, 3002218]    1.0             4      3002118
23  (3002218, 3002318]   10.0             6      3002218
24  (3002318, 3002418]    2.0             1      3002318
25  (3002418, 3002518]   19.0             5      3002418
26  (3002518, 3002618]    4.0             2      3002518
27  (3002618, 3002718]    0.0             3      3002618
28  (3002718, 3002818]    0.0             1      3002718
29  (3002818, 3002918]    0.0             2      3002818
30  (3002918, 3003018]    1.0             6      3002918
31  (3003018, 3003118]    2.0             4      3003018
32  (3003118, 3003218]    0.0             0      3003118
33  (3003218, 3003318]    0.0             1      3003218
34  (3003318, 3003418]    1.0             8      3003318
35  (3003418, 3003518]    0.0             3      3003418
36  (3003518, 3003618]    1.0             2      3003518
37  (3003618, 3003718]    3.0             4      3003618
38  (3003718, 3003818]    1.0             6      3003718
39  (3003818, 3003918]    0.0             3      3003818
40  (3003918, 3004018]    8.0             6      3003918
41  (3004018, 3004118]    0.0             0      3004018
42  (3004118, 3004218]    0.0             1      3004118
43  (3004218, 3004318]    5.0             6      3004218
44  (3004318, 3004418]    0.0             1      3004318
45  (3004418, 3004518]    0.0             1      3004418
46  (3004518, 3004618]    1.0             7      3004518
47  (3004618, 3004718]    0.0             0      3004618
48  (3004718, 3004818]    0.0             1      3004718
49  (3004818, 3004918]   13.0             8      3004818
(152618, 4)
bin_offset_0    category
TT_S0            float64
target_count       int64
starting_nt        int64
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         7.0      0            0      0     0
2         1.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   10.0      0            0      0     0
152614    3.0      0            0      0     0
152615    4.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         7.0             0                   0             0            0
2         1.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   10.0             0                   0             0            0
152614    3.0             0                   0             0            0
152615    4.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.10474518077815198
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 219187.0
cluster target count 572145
!!cluster density 0.3830969422087058
cluster signal 237724.0
cluster target count 127855
!!cluster density 1.8593250166203903

Labels mapping
 {0: 0, 1: 1}
DEBUG: 136632 15986

 +----------------------+-------------+----------------+-------+
| bin_offset_0         | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000018]   | 0.0         | 0              | ...   |
| (3000018, 3000118]   | 7.0         | 11             | ...   |
| (3000118, 3000218]   | 1.0         | 4              | ...   |
| (3000218, 3000318]   | 2.0         | 4              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261318, 18261418] | 3.0         | 15             | ...   |
| (18261418, 18261518] | 4.0         | 4              | ...   |
| (18261518, 18261618] | 0.0         | 3              | ...   |
| (18261618, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 136,632 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000023],   (3000023, 3000123],
                 (3000123, 3000223],   (3000223, 3000323],
                 (3000323, 3000423],   (3000423, 3000523],
                 (3000523, 3000623],   (3000623, 3000723],
                 (3000723, 3000823],   (3000823, 3000923],
               ...
               (18260723, 18260823], (18260823, 18260923],
               (18260923, 18261023], (18261023, 18261123],
               (18261123, 18261223], (18261223, 18261323],
               (18261323, 18261423], (18261423, 18261523],
               (18261523, 18261623], (18261623, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

         bin_offset_5  target_count
0  (3000018, 3000023]             1
1  (3000018, 3000023]             1
2  (3000023, 3000123]             1
3  (3000023, 3000123]             1
4  (3000023, 3000123]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

                bin_offset_5  target_count
699995  (18261523, 18261623]             1
699996  (18261523, 18261623]             1
699997  (18261623, 18261710]             1
699998  (18261623, 18261710]             1
699999  (18261623, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
          bin_offset_5  TT_S0  target_count starting_nt
0   (3000018, 3000023]    0.0             2     3000018
1   (3000023, 3000123]    7.0             9     3000023
2   (3000123, 3000223]    1.0             5     3000123
3   (3000223, 3000323]    2.0             3     3000223
4   (3000323, 3000423]    0.0             4     3000323
5   (3000423, 3000523]    0.0             2     3000423
6   (3000523, 3000623]    0.0             2     3000523
7   (3000623, 3000723]    0.0             4     3000623
8   (3000723, 3000823]    0.0             7     3000723
9   (3000823, 3000923]    0.0             4     3000823
10  (3000923, 3001023]    0.0             2     3000923
11  (3001023, 3001123]    2.0             6     3001023
12  (3001123, 3001223]    0.0             2     3001123
13  (3001223, 3001323]    0.0             5     3001223
14  (3001323, 3001423]    0.0             2     3001323
15  (3001423, 3001523]    1.0             6     3001423
16  (3001523, 3001623]    3.0             8     3001523
17  (3001623, 3001723]    3.0             8     3001623
18  (3001723, 3001823]    0.0             5     3001723
19  (3001823, 3001923]    0.0             3     3001823
20  (3001923, 3002023]    1.0             2     3001923
21  (3002023, 3002123]    0.0             2     3002023
22  (3002123, 3002223]    1.0             4     3002123
23  (3002223, 3002323]   10.0             6     3002223
24  (3002323, 3002423]   12.0             2     3002323
25  (3002423, 3002523]    9.0             5     3002423
26  (3002523, 3002623]    4.0             1     3002523
27  (3002623, 3002723]    0.0             3     3002623
28  (3002723, 3002823]    0.0             1     3002723
29  (3002823, 3002923]    0.0             2     3002823
30  (3002923, 3003023]    1.0             6     3002923
31  (3003023, 3003123]    2.0             4     3003023
32  (3003123, 3003223]    0.0             0     3003123
33  (3003223, 3003323]    0.0             2     3003223
34  (3003323, 3003423]    1.0             7     3003323
35  (3003423, 3003523]    0.0             3     3003423
36  (3003523, 3003623]    1.0             2     3003523
37  (3003623, 3003723]    3.0             4     3003623
38  (3003723, 3003823]    1.0             6     3003723
39  (3003823, 3003923]    1.0             4     3003823
40  (3003923, 3004023]    7.0             5     3003923
41  (3004023, 3004123]    0.0             0     3004023
42  (3004123, 3004223]    0.0             2     3004123
43  (3004223, 3004323]    5.0             5     3004223
44  (3004323, 3004423]    0.0             1     3004323
45  (3004423, 3004523]    0.0             2     3004423
46  (3004523, 3004623]    1.0             6     3004523
47  (3004623, 3004723]    0.0             0     3004623
48  (3004723, 3004823]    0.0             1     3004723
49  (3004823, 3004923]   13.0             8     3004823
(152618, 4)
bin_offset_5    category
TT_S0            float64
target_count       int64
starting_nt     category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         7.0      0            0      0     0
2         1.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   10.0      0            0      0     0
152614    3.0      0            0      0     0
152615    4.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         7.0             0                   0             0            0
2         1.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   10.0             0                   0             0            0
152614    3.0             0                   0             0            0
152615    4.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.15202662857592159
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 1 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 0 1 1
 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 165721.0
cluster target count 525610
!!cluster density 0.31529270752078536
cluster signal 291190.0
cluster target count 174390
!!cluster density 1.6697631744939503

Labels mapping
 {0: 0, 1: 1}
DEBUG: 129416 23202

 +----------------------+-------------+----------------+-------+
| bin_offset_5         | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000023]   | 0.0         | 2              | ...   |
| (3000123, 3000223]   | 1.0         | 5              | ...   |
| (3000223, 3000323]   | 2.0         | 3              | ...   |
| (3000323, 3000423]   | 0.0         | 4              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261323, 18261423] | 3.0         | 14             | ...   |
| (18261423, 18261523] | 4.0         | 4              | ...   |
| (18261523, 18261623] | 0.0         | 3              | ...   |
| (18261623, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 129,416 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000028],   (3000028, 3000128],
                 (3000128, 3000228],   (3000228, 3000328],
                 (3000328, 3000428],   (3000428, 3000528],
                 (3000528, 3000628],   (3000628, 3000728],
                 (3000728, 3000828],   (3000828, 3000928],
               ...
               (18260728, 18260828], (18260828, 18260928],
               (18260928, 18261028], (18261028, 18261128],
               (18261128, 18261228], (18261228, 18261328],
               (18261328, 18261428], (18261428, 18261528],
               (18261528, 18261628], (18261628, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_10  target_count
0  (3000018, 3000028]             1
1  (3000018, 3000028]             1
2  (3000018, 3000028]             1
3  (3000028, 3000128]             1
4  (3000028, 3000128]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_10  target_count
699995  (18261528, 18261628]             1
699996  (18261528, 18261628]             1
699997  (18261628, 18261710]             1
699998  (18261628, 18261710]             1
699999  (18261628, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_10  TT_S0  target_count starting_nt
0   (3000018, 3000028]    0.0             3     3000018
1   (3000028, 3000128]    7.0             8     3000028
2   (3000128, 3000228]    1.0             5     3000128
3   (3000228, 3000328]    2.0             3     3000228
4   (3000328, 3000428]    0.0             5     3000328
5   (3000428, 3000528]    0.0             1     3000428
6   (3000528, 3000628]    0.0             2     3000528
7   (3000628, 3000728]    0.0             4     3000628
8   (3000728, 3000828]    0.0             7     3000728
9   (3000828, 3000928]    0.0             4     3000828
10  (3000928, 3001028]    0.0             2     3000928
11  (3001028, 3001128]    2.0             6     3001028
12  (3001128, 3001228]    0.0             2     3001128
13  (3001228, 3001328]    0.0             5     3001228
14  (3001328, 3001428]    0.0             2     3001328
15  (3001428, 3001528]    1.0             6     3001428
16  (3001528, 3001628]    3.0             9     3001528
17  (3001628, 3001728]    3.0             7     3001628
18  (3001728, 3001828]    0.0             5     3001728
19  (3001828, 3001928]    0.0             3     3001828
20  (3001928, 3002028]    1.0             2     3001928
21  (3002028, 3002128]    0.0             2     3002028
22  (3002128, 3002228]    1.0             4     3002128
23  (3002228, 3002328]   10.0             6     3002228
24  (3002328, 3002428]   12.0             2     3002328
25  (3002428, 3002528]   13.0             6     3002428
26  (3002528, 3002628]    0.0             0     3002528
27  (3002628, 3002728]    0.0             3     3002628
28  (3002728, 3002828]    0.0             2     3002728
29  (3002828, 3002928]    0.0             1     3002828
30  (3002928, 3003028]    1.0             6     3002928
31  (3003028, 3003128]    2.0             4     3003028
32  (3003128, 3003228]    0.0             0     3003128
33  (3003228, 3003328]    0.0             3     3003228
34  (3003328, 3003428]    1.0             6     3003328
35  (3003428, 3003528]    0.0             3     3003428
36  (3003528, 3003628]    1.0             2     3003528
37  (3003628, 3003728]    3.0             4     3003628
38  (3003728, 3003828]    1.0             6     3003728
39  (3003828, 3003928]    1.0             4     3003828
40  (3003928, 3004028]    7.0             5     3003928
41  (3004028, 3004128]    0.0             0     3004028
42  (3004128, 3004228]    0.0             3     3004128
43  (3004228, 3004328]    5.0             4     3004228
44  (3004328, 3004428]    0.0             1     3004328
45  (3004428, 3004528]    0.0             3     3004428
46  (3004528, 3004628]    1.0             5     3004528
47  (3004628, 3004728]    0.0             0     3004628
48  (3004728, 3004828]    0.0             1     3004728
49  (3004828, 3004928]   13.0             8     3004828
(152618, 4)
bin_offset_10    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         7.0      0            0      0     0
2         1.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   10.0      0            0      0     0
152614    3.0      0            0      0     0
152615    4.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         7.0             0                   0             0            0
2         1.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   10.0             0                   0             0            0
152614    3.0             0                   0             0            0
152615    4.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.848438585225858
[1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 1 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 0
 0 0 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 0 0
 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1]
threshold density 1.30546
cluster signal 166125.0
cluster target count 526296
!!cluster density 0.31564936841625246
cluster signal 290786.0
cluster target count 173704
!!cluster density 1.6740316860866762

Labels mapping
 {1: 0, 0: 1}
DEBUG: 129487 23131

 +----------------------+-------------+----------------+-------+
| bin_offset_10        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000028]   | 0.0         | 3              | ...   |
| (3000128, 3000228]   | 1.0         | 5              | ...   |
| (3000228, 3000328]   | 2.0         | 3              | ...   |
| (3000328, 3000428]   | 0.0         | 5              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261328, 18261428] | 3.0         | 14             | ...   |
| (18261428, 18261528] | 4.0         | 4              | ...   |
| (18261528, 18261628] | 0.0         | 3              | ...   |
| (18261628, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 129,487 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000033],   (3000033, 3000133],
                 (3000133, 3000233],   (3000233, 3000333],
                 (3000333, 3000433],   (3000433, 3000533],
                 (3000533, 3000633],   (3000633, 3000733],
                 (3000733, 3000833],   (3000833, 3000933],
               ...
               (18260733, 18260833], (18260833, 18260933],
               (18260933, 18261033], (18261033, 18261133],
               (18261133, 18261233], (18261233, 18261333],
               (18261333, 18261433], (18261433, 18261533],
               (18261533, 18261633], (18261633, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_15  target_count
0  (3000018, 3000033]             1
1  (3000018, 3000033]             1
2  (3000018, 3000033]             1
3  (3000033, 3000133]             1
4  (3000033, 3000133]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_15  target_count
699995  (18261533, 18261633]             1
699996  (18261533, 18261633]             1
699997  (18261633, 18261710]             1
699998  (18261633, 18261710]             1
699999  (18261633, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_15  TT_S0  target_count starting_nt
0   (3000018, 3000033]    0.0             3     3000018
1   (3000033, 3000133]    8.0             9     3000033
2   (3000133, 3000233]    0.0             4     3000133
3   (3000233, 3000333]    2.0             3     3000233
4   (3000333, 3000433]    0.0             5     3000333
5   (3000433, 3000533]    0.0             1     3000433
6   (3000533, 3000633]    0.0             2     3000533
7   (3000633, 3000733]    0.0             4     3000633
8   (3000733, 3000833]    0.0             7     3000733
9   (3000833, 3000933]    0.0             4     3000833
10  (3000933, 3001033]    0.0             3     3000933
11  (3001033, 3001133]    2.0             5     3001033
12  (3001133, 3001233]    0.0             2     3001133
13  (3001233, 3001333]    0.0             5     3001233
14  (3001333, 3001433]    0.0             2     3001333
15  (3001433, 3001533]    1.0             7     3001433
16  (3001533, 3001633]    3.0             8     3001533
17  (3001633, 3001733]    3.0             7     3001633
18  (3001733, 3001833]    0.0             6     3001733
19  (3001833, 3001933]    0.0             2     3001833
20  (3001933, 3002033]    1.0             2     3001933
21  (3002033, 3002133]    0.0             3     3002033
22  (3002133, 3002233]    4.0             4     3002133
23  (3002233, 3002333]    7.0             5     3002233
24  (3002333, 3002433]   12.0             2     3002333
25  (3002433, 3002533]   13.0             6     3002433
26  (3002533, 3002633]    0.0             0     3002533
27  (3002633, 3002733]    0.0             3     3002633
28  (3002733, 3002833]    0.0             2     3002733
29  (3002833, 3002933]    0.0             1     3002833
30  (3002933, 3003033]    1.0             6     3002933
31  (3003033, 3003133]    2.0             4     3003033
32  (3003133, 3003233]    0.0             0     3003133
33  (3003233, 3003333]    0.0             4     3003233
34  (3003333, 3003433]    1.0             5     3003333
35  (3003433, 3003533]    0.0             3     3003433
36  (3003533, 3003633]    1.0             2     3003533
37  (3003633, 3003733]    3.0             5     3003633
38  (3003733, 3003833]    1.0             5     3003733
39  (3003833, 3003933]    1.0             4     3003833
40  (3003933, 3004033]    7.0             5     3003933
41  (3004033, 3004133]    0.0             0     3004033
42  (3004133, 3004233]    0.0             3     3004133
43  (3004233, 3004333]    5.0             4     3004233
44  (3004333, 3004433]    0.0             1     3004333
45  (3004433, 3004533]    0.0             3     3004433
46  (3004533, 3004633]    1.0             5     3004533
47  (3004633, 3004733]    0.0             0     3004633
48  (3004733, 3004833]    0.0             1     3004733
49  (3004833, 3004933]   13.0             8     3004833
(152618, 4)
bin_offset_15    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         8.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   13.0      0            0      0     0
152614    0.0      0            0      0     0
152615    4.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         8.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   13.0             0                   0             0            0
152614    0.0             0                   0             0            0
152615    4.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.10486312230536372
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 1 0 1 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 219126.0
cluster target count 572672
!!cluster density 0.3826378799731784
cluster signal 237785.0
cluster target count 127328
!!cluster density 1.8674996858507162

Labels mapping
 {0: 0, 1: 1}
DEBUG: 136614 16004

 +----------------------+-------------+----------------+-------+
| bin_offset_15        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000033]   | 0.0         | 3              | ...   |
| (3000033, 3000133]   | 8.0         | 9              | ...   |
| (3000133, 3000233]   | 0.0         | 4              | ...   |
| (3000233, 3000333]   | 2.0         | 3              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261333, 18261433] | 0.0         | 12             | ...   |
| (18261433, 18261533] | 4.0         | 4              | ...   |
| (18261533, 18261633] | 0.0         | 3              | ...   |
| (18261633, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 136,614 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000038],   (3000038, 3000138],
                 (3000138, 3000238],   (3000238, 3000338],
                 (3000338, 3000438],   (3000438, 3000538],
                 (3000538, 3000638],   (3000638, 3000738],
                 (3000738, 3000838],   (3000838, 3000938],
               ...
               (18260738, 18260838], (18260838, 18260938],
               (18260938, 18261038], (18261038, 18261138],
               (18261138, 18261238], (18261238, 18261338],
               (18261338, 18261438], (18261438, 18261538],
               (18261538, 18261638], (18261638, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_20  target_count
0  (3000018, 3000038]             1
1  (3000018, 3000038]             1
2  (3000018, 3000038]             1
3  (3000038, 3000138]             1
4  (3000038, 3000138]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_20  target_count
699995  (18261538, 18261638]             1
699996  (18261538, 18261638]             1
699997  (18261638, 18261710]             1
699998  (18261638, 18261710]             1
699999  (18261638, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_20  TT_S0  target_count starting_nt
0   (3000018, 3000038]    0.0             3     3000018
1   (3000038, 3000138]    8.0            10     3000038
2   (3000138, 3000238]    0.0             3     3000138
3   (3000238, 3000338]    2.0             3     3000238
4   (3000338, 3000438]    0.0             5     3000338
5   (3000438, 3000538]    0.0             1     3000438
6   (3000538, 3000638]    0.0             2     3000538
7   (3000638, 3000738]    0.0             5     3000638
8   (3000738, 3000838]    0.0             6     3000738
9   (3000838, 3000938]    0.0             4     3000838
10  (3000938, 3001038]    0.0             3     3000938
11  (3001038, 3001138]    2.0             5     3001038
12  (3001138, 3001238]    0.0             2     3001138
13  (3001238, 3001338]    0.0             5     3001238
14  (3001338, 3001438]    0.0             2     3001338
15  (3001438, 3001538]    1.0             7     3001438
16  (3001538, 3001638]    3.0             8     3001538
17  (3001638, 3001738]    3.0             7     3001638
18  (3001738, 3001838]    0.0             6     3001738
19  (3001838, 3001938]    0.0             2     3001838
20  (3001938, 3002038]    1.0             2     3001938
21  (3002038, 3002138]    0.0             3     3002038
22  (3002138, 3002238]    4.0             5     3002138
23  (3002238, 3002338]    7.0             4     3002238
24  (3002338, 3002438]   12.0             2     3002338
25  (3002438, 3002538]   13.0             6     3002438
26  (3002538, 3002638]    0.0             0     3002538
27  (3002638, 3002738]    0.0             3     3002638
28  (3002738, 3002838]    0.0             3     3002738
29  (3002838, 3002938]    0.0             0     3002838
30  (3002938, 3003038]    1.0             8     3002938
31  (3003038, 3003138]    2.0             2     3003038
32  (3003138, 3003238]    0.0             0     3003138
33  (3003238, 3003338]    0.0             4     3003238
34  (3003338, 3003438]    1.0             5     3003338
35  (3003438, 3003538]    0.0             3     3003438
36  (3003538, 3003638]    1.0             2     3003538
37  (3003638, 3003738]    3.0             5     3003638
38  (3003738, 3003838]    1.0             5     3003738
39  (3003838, 3003938]    1.0             4     3003838
40  (3003938, 3004038]    7.0             5     3003938
41  (3004038, 3004138]    0.0             0     3004038
42  (3004138, 3004238]    1.0             4     3004138
43  (3004238, 3004338]    4.0             3     3004238
44  (3004338, 3004438]    0.0             1     3004338
45  (3004438, 3004538]    0.0             3     3004438
46  (3004538, 3004638]    1.0             5     3004538
47  (3004638, 3004738]    0.0             0     3004638
48  (3004738, 3004838]    1.0             2     3004738
49  (3004838, 3004938]   12.0             7     3004838
(152618, 4)
bin_offset_20    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         8.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   13.0      0            0      0     0
152614    1.0      0            0      0     0
152615    3.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         8.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   13.0             0                   0             0            0
152614    1.0             0                   0             0            0
152615    3.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.15105688712995846
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 1 1 1 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 1 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 0
 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 166589.0
cluster target count 526759
!!cluster density 0.31625278353098857
cluster signal 290322.0
cluster target count 173241
!!cluster density 1.6758273157047119

Labels mapping
 {0: 0, 1: 1}
DEBUG: 129564 23054

 +----------------------+-------------+----------------+-------+
| bin_offset_20        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000038]   | 0.0         | 3              | ...   |
| (3000138, 3000238]   | 0.0         | 3              | ...   |
| (3000238, 3000338]   | 2.0         | 3              | ...   |
| (3000338, 3000438]   | 0.0         | 5              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261338, 18261438] | 1.0         | 12             | ...   |
| (18261438, 18261538] | 3.0         | 4              | ...   |
| (18261538, 18261638] | 0.0         | 2              | ...   |
| (18261638, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 129,564 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000043],   (3000043, 3000143],
                 (3000143, 3000243],   (3000243, 3000343],
                 (3000343, 3000443],   (3000443, 3000543],
                 (3000543, 3000643],   (3000643, 3000743],
                 (3000743, 3000843],   (3000843, 3000943],
               ...
               (18260743, 18260843], (18260843, 18260943],
               (18260943, 18261043], (18261043, 18261143],
               (18261143, 18261243], (18261243, 18261343],
               (18261343, 18261443], (18261443, 18261543],
               (18261543, 18261643], (18261643, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_25  target_count
0  (3000018, 3000043]             1
1  (3000018, 3000043]             1
2  (3000018, 3000043]             1
3  (3000018, 3000043]             1
4  (3000043, 3000143]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_25  target_count
699995  (18261543, 18261643]             1
699996  (18261543, 18261643]             1
699997  (18261643, 18261710]             1
699998  (18261643, 18261710]             1
699999  (18261643, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_25  TT_S0  target_count starting_nt
0   (3000018, 3000043]    4.0             4     3000018
1   (3000043, 3000143]    4.0             9     3000043
2   (3000143, 3000243]    0.0             3     3000143
3   (3000243, 3000343]    2.0             3     3000243
4   (3000343, 3000443]    0.0             5     3000343
5   (3000443, 3000543]    0.0             1     3000443
6   (3000543, 3000643]    0.0             2     3000543
7   (3000643, 3000743]    0.0             5     3000643
8   (3000743, 3000843]    0.0             6     3000743
9   (3000843, 3000943]    0.0             4     3000843
10  (3000943, 3001043]    2.0             4     3000943
11  (3001043, 3001143]    0.0             4     3001043
12  (3001143, 3001243]    0.0             2     3001143
13  (3001243, 3001343]    0.0             5     3001243
14  (3001343, 3001443]    0.0             2     3001343
15  (3001443, 3001543]    1.0             7     3001443
16  (3001543, 3001643]    3.0             8     3001543
17  (3001643, 3001743]    3.0             8     3001643
18  (3001743, 3001843]    0.0             5     3001743
19  (3001843, 3001943]    0.0             2     3001843
20  (3001943, 3002043]    1.0             2     3001943
21  (3002043, 3002143]    0.0             3     3002043
22  (3002143, 3002243]    4.0             5     3002143
23  (3002243, 3002343]    7.0             4     3002243
24  (3002343, 3002443]   12.0             3     3002343
25  (3002443, 3002543]   13.0             5     3002443
26  (3002543, 3002643]    0.0             0     3002543
27  (3002643, 3002743]    0.0             3     3002643
28  (3002743, 3002843]    0.0             3     3002743
29  (3002843, 3002943]    0.0             0     3002843
30  (3002943, 3003043]    1.0             8     3002943
31  (3003043, 3003143]    2.0             2     3003043
32  (3003143, 3003243]    0.0             0     3003143
33  (3003243, 3003343]    1.0             5     3003243
34  (3003343, 3003443]    0.0             4     3003343
35  (3003443, 3003543]    0.0             3     3003443
36  (3003543, 3003643]    1.0             2     3003543
37  (3003643, 3003743]    3.0             5     3003643
38  (3003743, 3003843]    1.0             5     3003743
39  (3003843, 3003943]    1.0             5     3003843
40  (3003943, 3004043]    7.0             4     3003943
41  (3004043, 3004143]    0.0             0     3004043
42  (3004143, 3004243]    1.0             4     3004143
43  (3004243, 3004343]    4.0             3     3004243
44  (3004343, 3004443]    0.0             1     3004343
45  (3004443, 3004543]    0.0             3     3004443
46  (3004543, 3004643]    1.0             5     3004543
47  (3004643, 3004743]    0.0             0     3004643
48  (3004743, 3004843]    2.0             3     3004743
49  (3004843, 3004943]   11.0             6     3004843
(152618, 4)
bin_offset_25    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         4.0      0            0      0     0
1         4.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   13.0      0            0      0     0
152614    1.0      0            0      0     0
152615    3.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         4.0             0                   0             0            0
1         4.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   13.0             0                   0             0            0
152614    1.0             0                   0             0            0
152615    3.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.10489588384070031
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 1 0 1 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 219194.0
cluster target count 572548
!!cluster density 0.3828395173854419
cluster signal 237717.0
cluster target count 127452
!!cluster density 1.8651492326522927

Labels mapping
 {0: 0, 1: 1}
DEBUG: 136609 16009

 +----------------------+-------------+----------------+-------+
| bin_offset_25        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000043]   | 4.0         | 4              | ...   |
| (3000043, 3000143]   | 4.0         | 9              | ...   |
| (3000143, 3000243]   | 0.0         | 3              | ...   |
| (3000243, 3000343]   | 2.0         | 3              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261343, 18261443] | 1.0         | 12             | ...   |
| (18261443, 18261543] | 3.0         | 4              | ...   |
| (18261543, 18261643] | 0.0         | 2              | ...   |
| (18261643, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 136,609 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000048],   (3000048, 3000148],
                 (3000148, 3000248],   (3000248, 3000348],
                 (3000348, 3000448],   (3000448, 3000548],
                 (3000548, 3000648],   (3000648, 3000748],
                 (3000748, 3000848],   (3000848, 3000948],
               ...
               (18260748, 18260848], (18260848, 18260948],
               (18260948, 18261048], (18261048, 18261148],
               (18261148, 18261248], (18261248, 18261348],
               (18261348, 18261448], (18261448, 18261548],
               (18261548, 18261648], (18261648, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_30  target_count
0  (3000018, 3000048]             1
1  (3000018, 3000048]             1
2  (3000018, 3000048]             1
3  (3000018, 3000048]             1
4  (3000048, 3000148]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_30  target_count
699995  (18261548, 18261648]             1
699996  (18261548, 18261648]             1
699997  (18261648, 18261710]             1
699998  (18261648, 18261710]             1
699999  (18261648, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_30  TT_S0  target_count starting_nt
0   (3000018, 3000048]    4.0             4     3000018
1   (3000048, 3000148]    4.0             9     3000048
2   (3000148, 3000248]    0.0             3     3000148
3   (3000248, 3000348]    2.0             3     3000248
4   (3000348, 3000448]    0.0             5     3000348
5   (3000448, 3000548]    0.0             1     3000448
6   (3000548, 3000648]    0.0             2     3000548
7   (3000648, 3000748]    0.0             5     3000648
8   (3000748, 3000848]    0.0             6     3000748
9   (3000848, 3000948]    0.0             5     3000848
10  (3000948, 3001048]    2.0             3     3000948
11  (3001048, 3001148]    0.0             4     3001048
12  (3001148, 3001248]    0.0             2     3001148
13  (3001248, 3001348]    0.0             5     3001248
14  (3001348, 3001448]    0.0             2     3001348
15  (3001448, 3001548]    1.0             8     3001448
16  (3001548, 3001648]    5.0             8     3001548
17  (3001648, 3001748]    1.0             7     3001648
18  (3001748, 3001848]    0.0             5     3001748
19  (3001848, 3001948]    0.0             2     3001848
20  (3001948, 3002048]    1.0             2     3001948
21  (3002048, 3002148]    0.0             3     3002048
22  (3002148, 3002248]    4.0             5     3002148
23  (3002248, 3002348]    7.0             4     3002248
24  (3002348, 3002448]   14.0             4     3002348
25  (3002448, 3002548]   11.0             4     3002448
26  (3002548, 3002648]    0.0             1     3002548
27  (3002648, 3002748]    0.0             2     3002648
28  (3002748, 3002848]    0.0             3     3002748
29  (3002848, 3002948]    0.0             0     3002848
30  (3002948, 3003048]    1.0             8     3002948
31  (3003048, 3003148]    2.0             2     3003048
32  (3003148, 3003248]    0.0             0     3003148
33  (3003248, 3003348]    1.0             5     3003248
34  (3003348, 3003448]    0.0             4     3003348
35  (3003448, 3003548]    0.0             4     3003448
36  (3003548, 3003648]    1.0             1     3003548
37  (3003648, 3003748]    3.0             5     3003648
38  (3003748, 3003848]    1.0             5     3003748
39  (3003848, 3003948]    1.0             5     3003848
40  (3003948, 3004048]    7.0             4     3003948
41  (3004048, 3004148]    0.0             0     3004048
42  (3004148, 3004248]    1.0             4     3004148
43  (3004248, 3004348]    4.0             3     3004248
44  (3004348, 3004448]    0.0             1     3004348
45  (3004448, 3004548]    0.0             3     3004448
46  (3004548, 3004648]    1.0             5     3004548
47  (3004648, 3004748]    0.0             0     3004648
48  (3004748, 3004848]    2.0             3     3004748
49  (3004848, 3004948]   11.0             6     3004848
(152618, 4)
bin_offset_30    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         4.0      0            0      0     0
1         4.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   13.0      0            0      0     0
152614    1.0      0            0      0     0
152615    3.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         4.0             0                   0             0            0
1         4.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   13.0             0                   0             0            0
152614    1.0             0                   0             0            0
152615    3.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.8746412611880643
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 1 1 0 1 0 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0
 0 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 0 0 1 0 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1]
threshold density 1.30546
cluster signal 194194.0
cluster target count 551544
!!cluster density 0.35209158290181747
cluster signal 262717.0
cluster target count 148456
!!cluster density 1.7696623915503584

Labels mapping
 {1: 0, 0: 1}
DEBUG: 133486 19132

 +----------------------+-------------+----------------+-------+
| bin_offset_30        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000048]   | 4.0         | 4              | ...   |
| (3000048, 3000148]   | 4.0         | 9              | ...   |
| (3000148, 3000248]   | 0.0         | 3              | ...   |
| (3000248, 3000348]   | 2.0         | 3              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261348, 18261448] | 1.0         | 10             | ...   |
| (18261448, 18261548] | 3.0         | 4              | ...   |
| (18261548, 18261648] | 0.0         | 2              | ...   |
| (18261648, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 133,486 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000053],   (3000053, 3000153],
                 (3000153, 3000253],   (3000253, 3000353],
                 (3000353, 3000453],   (3000453, 3000553],
                 (3000553, 3000653],   (3000653, 3000753],
                 (3000753, 3000853],   (3000853, 3000953],
               ...
               (18260753, 18260853], (18260853, 18260953],
               (18260953, 18261053], (18261053, 18261153],
               (18261153, 18261253], (18261253, 18261353],
               (18261353, 18261453], (18261453, 18261553],
               (18261553, 18261653], (18261653, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_35  target_count
0  (3000018, 3000053]             1
1  (3000018, 3000053]             1
2  (3000018, 3000053]             1
3  (3000018, 3000053]             1
4  (3000053, 3000153]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_35  target_count
699995  (18261553, 18261653]             1
699996  (18261553, 18261653]             1
699997  (18261653, 18261710]             1
699998  (18261653, 18261710]             1
699999  (18261653, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_35  TT_S0  target_count starting_nt
0   (3000018, 3000053]    4.0             4     3000018
1   (3000053, 3000153]    4.0             9     3000053
2   (3000153, 3000253]    0.0             3     3000153
3   (3000253, 3000353]    2.0             4     3000253
4   (3000353, 3000453]    0.0             4     3000353
5   (3000453, 3000553]    0.0             1     3000453
6   (3000553, 3000653]    0.0             2     3000553
7   (3000653, 3000753]    0.0             6     3000653
8   (3000753, 3000853]    0.0             5     3000753
9   (3000853, 3000953]    0.0             5     3000853
10  (3000953, 3001053]    2.0             3     3000953
11  (3001053, 3001153]    0.0             4     3001053
12  (3001153, 3001253]    0.0             2     3001153
13  (3001253, 3001353]    0.0             5     3001253
14  (3001353, 3001453]    0.0             3     3001353
15  (3001453, 3001553]    1.0             8     3001453
16  (3001553, 3001653]    5.0             7     3001553
17  (3001653, 3001753]    1.0             7     3001653
18  (3001753, 3001853]    0.0             5     3001753
19  (3001853, 3001953]    0.0             2     3001853
20  (3001953, 3002053]    1.0             2     3001953
21  (3002053, 3002153]    0.0             3     3002053
22  (3002153, 3002253]    4.0             6     3002153
23  (3002253, 3002353]    7.0             3     3002253
24  (3002353, 3002453]   14.0             4     3002353
25  (3002453, 3002553]   11.0             4     3002453
26  (3002553, 3002653]    0.0             1     3002553
27  (3002653, 3002753]    0.0             2     3002653
28  (3002753, 3002853]    0.0             3     3002753
29  (3002853, 3002953]    0.0             1     3002853
30  (3002953, 3003053]    1.0             7     3002953
31  (3003053, 3003153]    2.0             2     3003053
32  (3003153, 3003253]    0.0             0     3003153
33  (3003253, 3003353]    1.0             5     3003253
34  (3003353, 3003453]    0.0             4     3003353
35  (3003453, 3003553]    0.0             4     3003453
36  (3003553, 3003653]    1.0             1     3003553
37  (3003653, 3003753]    3.0             5     3003653
38  (3003753, 3003853]    1.0             5     3003753
39  (3003853, 3003953]    1.0             6     3003853
40  (3003953, 3004053]    7.0             3     3003953
41  (3004053, 3004153]    0.0             0     3004053
42  (3004153, 3004253]    1.0             4     3004153
43  (3004253, 3004353]    4.0             3     3004253
44  (3004353, 3004453]    0.0             1     3004353
45  (3004453, 3004553]    0.0             3     3004453
46  (3004553, 3004653]    1.0             5     3004553
47  (3004653, 3004753]    0.0             0     3004653
48  (3004753, 3004853]   10.0             4     3004753
49  (3004853, 3004953]    3.0             5     3004853
(152618, 4)
bin_offset_35    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         4.0      0            0      0     0
1         4.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   13.0      0            0      0     0
152614    1.0      0            0      0     0
152615    3.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         4.0             0                   0             0            0
1         4.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   13.0             0                   0             0            0
152614    1.0             0                   0             0            0
152615    3.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.8482027021714346
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 1 1 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 1 1 0 1 0 1 0
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0
 0 0 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 1 1 1 1 0 1
 1 1 1 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1]
threshold density 1.30546
cluster signal 165964.0
cluster target count 526262
!!cluster density 0.31536383018344477
cluster signal 290947.0
cluster target count 173738
!!cluster density 1.674630765865844

Labels mapping
 {1: 0, 0: 1}
DEBUG: 129451 23167

 +----------------------+-------------+----------------+-------+
| bin_offset_35        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000053]   | 4.0         | 4              | ...   |
| (3000053, 3000153]   | 4.0         | 9              | ...   |
| (3000153, 3000253]   | 0.0         | 3              | ...   |
| (3000253, 3000353]   | 2.0         | 4              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261353, 18261453] | 1.0         | 9              | ...   |
| (18261453, 18261553] | 3.0         | 4              | ...   |
| (18261553, 18261653] | 0.0         | 2              | ...   |
| (18261653, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 129,451 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000058],   (3000058, 3000158],
                 (3000158, 3000258],   (3000258, 3000358],
                 (3000358, 3000458],   (3000458, 3000558],
                 (3000558, 3000658],   (3000658, 3000758],
                 (3000758, 3000858],   (3000858, 3000958],
               ...
               (18260758, 18260858], (18260858, 18260958],
               (18260958, 18261058], (18261058, 18261158],
               (18261158, 18261258], (18261258, 18261358],
               (18261358, 18261458], (18261458, 18261558],
               (18261558, 18261658], (18261658, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_40  target_count
0  (3000018, 3000058]             1
1  (3000018, 3000058]             1
2  (3000018, 3000058]             1
3  (3000018, 3000058]             1
4  (3000058, 3000158]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_40  target_count
699995  (18261558, 18261658]             1
699996  (18261558, 18261658]             1
699997  (18261658, 18261710]             1
699998  (18261658, 18261710]             1
699999  (18261658, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_40  TT_S0  target_count starting_nt
0   (3000018, 3000058]    4.0             4     3000018
1   (3000058, 3000158]    4.0             9     3000058
2   (3000158, 3000258]    0.0             3     3000158
3   (3000258, 3000358]    2.0             5     3000258
4   (3000358, 3000458]    0.0             3     3000358
5   (3000458, 3000558]    0.0             1     3000458
6   (3000558, 3000658]    0.0             2     3000558
7   (3000658, 3000758]    0.0             6     3000658
8   (3000758, 3000858]    0.0             5     3000758
9   (3000858, 3000958]    0.0             5     3000858
10  (3000958, 3001058]    2.0             5     3000958
11  (3001058, 3001158]    0.0             2     3001058
12  (3001158, 3001258]    0.0             2     3001158
13  (3001258, 3001358]    0.0             5     3001258
14  (3001358, 3001458]    0.0             4     3001358
15  (3001458, 3001558]    1.0             7     3001458
16  (3001558, 3001658]    5.0             7     3001558
17  (3001658, 3001758]    1.0             7     3001658
18  (3001758, 3001858]    0.0             5     3001758
19  (3001858, 3001958]    0.0             2     3001858
20  (3001958, 3002058]    1.0             2     3001958
21  (3002058, 3002158]    0.0             3     3002058
22  (3002158, 3002258]    4.0             6     3002158
23  (3002258, 3002358]    9.0             4     3002258
24  (3002358, 3002458]   19.0             4     3002358
25  (3002458, 3002558]    4.0             3     3002458
26  (3002558, 3002658]    0.0             1     3002558
27  (3002658, 3002758]    0.0             3     3002658
28  (3002758, 3002858]    0.0             2     3002758
29  (3002858, 3002958]    0.0             1     3002858
30  (3002958, 3003058]    3.0             8     3002958
31  (3003058, 3003158]    0.0             1     3003058
32  (3003158, 3003258]    0.0             0     3003158
33  (3003258, 3003358]    1.0             6     3003258
34  (3003358, 3003458]    0.0             3     3003358
35  (3003458, 3003558]    0.0             4     3003458
36  (3003558, 3003658]    1.0             1     3003558
37  (3003658, 3003758]    4.0             6     3003658
38  (3003758, 3003858]    0.0             4     3003758
39  (3003858, 3003958]    1.0             6     3003858
40  (3003958, 3004058]    7.0             3     3003958
41  (3004058, 3004158]    0.0             0     3004058
42  (3004158, 3004258]    1.0             4     3004158
43  (3004258, 3004358]    4.0             3     3004258
44  (3004358, 3004458]    0.0             1     3004358
45  (3004458, 3004558]    0.0             5     3004458
46  (3004558, 3004658]    1.0             3     3004558
47  (3004658, 3004758]    0.0             0     3004658
48  (3004758, 3004858]   10.0             4     3004758
49  (3004858, 3004958]    3.0             5     3004858
(152618, 4)
bin_offset_40    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         4.0      0            0      0     0
1         4.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   13.0      0            0      0     0
152614    4.0      0            0      0     0
152615    0.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         4.0             0                   0             0            0
1         4.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   13.0             0                   0             0            0
152614    4.0             0                   0             0            0
152615    0.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.1520659424183255
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 1 1 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 0 0 0 0 1 0
 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 165594.0
cluster target count 525957
!!cluster density 0.31484322862895636
cluster signal 291317.0
cluster target count 174043
!!cluster density 1.6738219865205726

Labels mapping
 {0: 0, 1: 1}
DEBUG: 129410 23208

 +----------------------+-------------+----------------+-------+
| bin_offset_40        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000058]   | 4.0         | 4              | ...   |
| (3000058, 3000158]   | 4.0         | 9              | ...   |
| (3000158, 3000258]   | 0.0         | 3              | ...   |
| (3000258, 3000358]   | 2.0         | 5              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261358, 18261458] | 4.0         | 10             | ...   |
| (18261458, 18261558] | 0.0         | 2              | ...   |
| (18261558, 18261658] | 0.0         | 2              | ...   |
| (18261658, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 129,410 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000063],   (3000063, 3000163],
                 (3000163, 3000263],   (3000263, 3000363],
                 (3000363, 3000463],   (3000463, 3000563],
                 (3000563, 3000663],   (3000663, 3000763],
                 (3000763, 3000863],   (3000863, 3000963],
               ...
               (18260763, 18260863], (18260863, 18260963],
               (18260963, 18261063], (18261063, 18261163],
               (18261163, 18261263], (18261263, 18261363],
               (18261363, 18261463], (18261463, 18261563],
               (18261563, 18261663], (18261663, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_45  target_count
0  (3000018, 3000063]             1
1  (3000018, 3000063]             1
2  (3000018, 3000063]             1
3  (3000018, 3000063]             1
4  (3000063, 3000163]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_45  target_count
699995  (18261563, 18261663]             1
699996  (18261563, 18261663]             1
699997  (18261663, 18261710]             1
699998  (18261663, 18261710]             1
699999  (18261663, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_45  TT_S0  target_count starting_nt
0   (3000018, 3000063]    4.0             4     3000018
1   (3000063, 3000163]    4.0            10     3000063
2   (3000163, 3000263]    0.0             2     3000163
3   (3000263, 3000363]    2.0             5     3000263
4   (3000363, 3000463]    0.0             3     3000363
5   (3000463, 3000563]    0.0             1     3000463
6   (3000563, 3000663]    0.0             3     3000563
7   (3000663, 3000763]    0.0             5     3000663
8   (3000763, 3000863]    0.0             5     3000763
9   (3000863, 3000963]    0.0             5     3000863
10  (3000963, 3001063]    2.0             6     3000963
11  (3001063, 3001163]    0.0             2     3001063
12  (3001163, 3001263]    0.0             2     3001163
13  (3001263, 3001363]    0.0             5     3001263
14  (3001363, 3001463]    0.0             3     3001363
15  (3001463, 3001563]    1.0             7     3001463
16  (3001563, 3001663]    6.0             8     3001563
17  (3001663, 3001763]    0.0             7     3001663
18  (3001763, 3001863]    0.0             5     3001763
19  (3001863, 3001963]    0.0             1     3001863
20  (3001963, 3002063]    1.0             2     3001963
21  (3002063, 3002163]    0.0             3     3002063
22  (3002163, 3002263]    4.0             6     3002163
23  (3002263, 3002363]    9.0             4     3002263
24  (3002363, 3002463]   19.0             4     3002363
25  (3002463, 3002563]    4.0             3     3002463
26  (3002563, 3002663]    0.0             1     3002563
27  (3002663, 3002763]    0.0             3     3002663
28  (3002763, 3002863]    0.0             2     3002763
29  (3002863, 3002963]    0.0             1     3002863
30  (3002963, 3003063]    3.0             8     3002963
31  (3003063, 3003163]    0.0             1     3003063
32  (3003163, 3003263]    0.0             0     3003163
33  (3003263, 3003363]    1.0             7     3003263
34  (3003363, 3003463]    0.0             3     3003363
35  (3003463, 3003563]    0.0             3     3003463
36  (3003563, 3003663]    1.0             1     3003563
37  (3003663, 3003763]    4.0             8     3003663
38  (3003763, 3003863]    0.0             2     3003763
39  (3003863, 3003963]    6.0             7     3003863
40  (3003963, 3004063]    2.0             2     3003963
41  (3004063, 3004163]    0.0             0     3004063
42  (3004163, 3004263]    1.0             4     3004163
43  (3004263, 3004363]    4.0             3     3004263
44  (3004363, 3004463]    0.0             1     3004363
45  (3004463, 3004563]    0.0             5     3004463
46  (3004563, 3004663]    1.0             3     3004563
47  (3004663, 3004763]    0.0             0     3004663
48  (3004763, 3004863]   10.0             4     3004763
49  (3004863, 3004963]    3.0             5     3004863
(152618, 4)
bin_offset_45    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         4.0      0            0      0     0
1         4.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   13.0      0            0      0     0
152614    4.0      0            0      0     0
152615    0.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         4.0             0                   0             0            0
1         4.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   13.0             0                   0             0            0
152614    4.0             0                   0             0            0
152615    0.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.15218388394553722
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 1 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0
 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 165593.0
cluster target count 525792
!!cluster density 0.3149401284157994
cluster signal 291318.0
cluster target count 174208
!!cluster density 1.672242376928729

Labels mapping
 {0: 0, 1: 1}
DEBUG: 129392 23226

 +----------------------+-------------+----------------+-------+
| bin_offset_45        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000063]   | 4.0         | 4              | ...   |
| (3000063, 3000163]   | 4.0         | 10             | ...   |
| (3000163, 3000263]   | 0.0         | 2              | ...   |
| (3000263, 3000363]   | 2.0         | 5              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261363, 18261463] | 4.0         | 9              | ...   |
| (18261463, 18261563] | 0.0         | 2              | ...   |
| (18261563, 18261663] | 0.0         | 2              | ...   |
| (18261663, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 129,392 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000068],   (3000068, 3000168],
                 (3000168, 3000268],   (3000268, 3000368],
                 (3000368, 3000468],   (3000468, 3000568],
                 (3000568, 3000668],   (3000668, 3000768],
                 (3000768, 3000868],   (3000868, 3000968],
               ...
               (18260768, 18260868], (18260868, 18260968],
               (18260968, 18261068], (18261068, 18261168],
               (18261168, 18261268], (18261268, 18261368],
               (18261368, 18261468], (18261468, 18261568],
               (18261568, 18261668], (18261668, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_50  target_count
0  (3000018, 3000068]             1
1  (3000018, 3000068]             1
2  (3000018, 3000068]             1
3  (3000018, 3000068]             1
4  (3000018, 3000068]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_50  target_count
699995  (18261568, 18261668]             1
699996  (18261568, 18261668]             1
699997  (18261668, 18261710]             1
699998  (18261668, 18261710]             1
699999  (18261668, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_50  TT_S0  target_count starting_nt
0   (3000018, 3000068]    4.0             5     3000018
1   (3000068, 3000168]    4.0             9     3000068
2   (3000168, 3000268]    0.0             2     3000168
3   (3000268, 3000368]    2.0             5     3000268
4   (3000368, 3000468]    0.0             3     3000368
5   (3000468, 3000568]    0.0             1     3000468
6   (3000568, 3000668]    0.0             3     3000568
7   (3000668, 3000768]    0.0             5     3000668
8   (3000768, 3000868]    0.0             5     3000768
9   (3000868, 3000968]    0.0             5     3000868
10  (3000968, 3001068]    2.0             6     3000968
11  (3001068, 3001168]    0.0             2     3001068
12  (3001168, 3001268]    0.0             2     3001168
13  (3001268, 3001368]    0.0             5     3001268
14  (3001368, 3001468]    0.0             3     3001368
15  (3001468, 3001568]    4.0             9     3001468
16  (3001568, 3001668]    3.0             6     3001568
17  (3001668, 3001768]    0.0             7     3001668
18  (3001768, 3001868]    0.0             5     3001768
19  (3001868, 3001968]    0.0             1     3001868
20  (3001968, 3002068]    1.0             2     3001968
21  (3002068, 3002168]    0.0             3     3002068
22  (3002168, 3002268]    4.0             6     3002168
23  (3002268, 3002368]    9.0             4     3002268
24  (3002368, 3002468]   19.0             4     3002368
25  (3002468, 3002568]    4.0             3     3002468
26  (3002568, 3002668]    0.0             1     3002568
27  (3002668, 3002768]    0.0             3     3002668
28  (3002768, 3002868]    0.0             2     3002768
29  (3002868, 3002968]    0.0             1     3002868
30  (3002968, 3003068]    3.0             9     3002968
31  (3003068, 3003168]    0.0             0     3003068
32  (3003168, 3003268]    0.0             0     3003168
33  (3003268, 3003368]    1.0             7     3003268
34  (3003368, 3003468]    0.0             3     3003368
35  (3003468, 3003568]    0.0             3     3003468
36  (3003568, 3003668]    1.0             1     3003568
37  (3003668, 3003768]    4.0             8     3003668
38  (3003768, 3003868]    0.0             2     3003768
39  (3003868, 3003968]    6.0             7     3003868
40  (3003968, 3004068]    2.0             2     3003968
41  (3004068, 3004168]    0.0             0     3004068
42  (3004168, 3004268]    3.0             5     3004168
43  (3004268, 3004368]    2.0             3     3004268
44  (3004368, 3004468]    0.0             0     3004368
45  (3004468, 3004568]    0.0             6     3004468
46  (3004568, 3004668]    1.0             2     3004568
47  (3004668, 3004768]    0.0             0     3004668
48  (3004768, 3004868]   10.0             5     3004768
49  (3004868, 3004968]    3.0             4     3004868
(152618, 4)
bin_offset_50    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         4.0      0            0      0     0
1         4.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   13.0      0            0      0     0
152614    4.0      0            0      0     0
152615    0.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         4.0             0                   0             0            0
1         4.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   13.0             0                   0             0            0
152614    4.0             0                   0             0            0
152615    0.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.847468843779895
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 1 0 1 1 0 1 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 0 0 0 1 1 0 0 1 0 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0
 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 1 0 0 1 1 1 1 0 1
 1 1 1 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1]
threshold density 1.30546
cluster signal 165267.0
cluster target count 525382
!!cluster density 0.31456540193611504
cluster signal 291644.0
cluster target count 174618
!!cluster density 1.670182913559885

Labels mapping
 {1: 0, 0: 1}
DEBUG: 129339 23279

 +----------------------+-------------+----------------+-------+
| bin_offset_50        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000068]   | 4.0         | 5              | ...   |
| (3000068, 3000168]   | 4.0         | 9              | ...   |
| (3000168, 3000268]   | 0.0         | 2              | ...   |
| (3000268, 3000368]   | 2.0         | 5              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261368, 18261468] | 4.0         | 8              | ...   |
| (18261468, 18261568] | 0.0         | 2              | ...   |
| (18261568, 18261668] | 0.0         | 2              | ...   |
| (18261668, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 129,339 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000073],   (3000073, 3000173],
                 (3000173, 3000273],   (3000273, 3000373],
                 (3000373, 3000473],   (3000473, 3000573],
                 (3000573, 3000673],   (3000673, 3000773],
                 (3000773, 3000873],   (3000873, 3000973],
               ...
               (18260773, 18260873], (18260873, 18260973],
               (18260973, 18261073], (18261073, 18261173],
               (18261173, 18261273], (18261273, 18261373],
               (18261373, 18261473], (18261473, 18261573],
               (18261573, 18261673], (18261673, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_55  target_count
0  (3000018, 3000073]             1
1  (3000018, 3000073]             1
2  (3000018, 3000073]             1
3  (3000018, 3000073]             1
4  (3000018, 3000073]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_55  target_count
699995  (18261573, 18261673]             1
699996  (18261573, 18261673]             1
699997  (18261673, 18261710]             1
699998  (18261673, 18261710]             1
699999  (18261673, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_55  TT_S0  target_count starting_nt
0   (3000018, 3000073]    4.0             5     3000018
1   (3000073, 3000173]    4.0            10     3000073
2   (3000173, 3000273]    0.0             1     3000173
3   (3000273, 3000373]    2.0             5     3000273
4   (3000373, 3000473]    0.0             3     3000373
5   (3000473, 3000573]    0.0             1     3000473
6   (3000573, 3000673]    0.0             4     3000573
7   (3000673, 3000773]    0.0             4     3000673
8   (3000773, 3000873]    0.0             6     3000773
9   (3000873, 3000973]    0.0             4     3000873
10  (3000973, 3001073]    2.0             6     3000973
11  (3001073, 3001173]    0.0             2     3001073
12  (3001173, 3001273]    0.0             2     3001173
13  (3001273, 3001373]    0.0             5     3001273
14  (3001373, 3001473]    0.0             3     3001373
15  (3001473, 3001573]    4.0             9     3001473
16  (3001573, 3001673]    3.0             6     3001573
17  (3001673, 3001773]    0.0             7     3001673
18  (3001773, 3001873]    0.0             5     3001773
19  (3001873, 3001973]    0.0             1     3001873
20  (3001973, 3002073]    1.0             2     3001973
21  (3002073, 3002173]    0.0             3     3002073
22  (3002173, 3002273]    4.0             7     3002173
23  (3002273, 3002373]    9.0             3     3002273
24  (3002373, 3002473]   19.0             4     3002373
25  (3002473, 3002573]    4.0             3     3002473
26  (3002573, 3002673]    0.0             1     3002573
27  (3002673, 3002773]    0.0             3     3002673
28  (3002773, 3002873]    0.0             2     3002773
29  (3002873, 3002973]    1.0             2     3002873
30  (3002973, 3003073]    2.0             8     3002973
31  (3003073, 3003173]    0.0             0     3003073
32  (3003173, 3003273]    0.0             0     3003173
33  (3003273, 3003373]    1.0             8     3003273
34  (3003373, 3003473]    0.0             2     3003373
35  (3003473, 3003573]    0.0             3     3003473
36  (3003573, 3003673]    1.0             2     3003573
37  (3003673, 3003773]    4.0             8     3003673
38  (3003773, 3003873]    0.0             1     3003773
39  (3003873, 3003973]    7.0             8     3003873
40  (3003973, 3004073]    1.0             1     3003973
41  (3004073, 3004173]    0.0             0     3004073
42  (3004173, 3004273]    3.0             5     3004173
43  (3004273, 3004373]    2.0             3     3004273
44  (3004373, 3004473]    0.0             0     3004373
45  (3004473, 3004573]    0.0             6     3004473
46  (3004573, 3004673]    1.0             2     3004573
47  (3004673, 3004773]    0.0             0     3004673
48  (3004773, 3004873]   10.0             6     3004773
49  (3004873, 3004973]    3.0             3     3004873
(152618, 4)
bin_offset_55    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         4.0      0            0      0     0
1         4.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   13.0      0            0      0     0
152614    4.0      0            0      0     0
152615    0.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         4.0             0                   0             0            0
1         4.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   13.0             0                   0             0            0
152614    4.0             0                   0             0            0
152615    0.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.1526032315978456
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0
 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 165139.0
cluster target count 525308
!!cluster density 0.31436604810891894
cluster signal 291772.0
cluster target count 174692
!!cluster density 1.6702081377510132

Labels mapping
 {0: 0, 1: 1}
DEBUG: 129328 23290

 +----------------------+-------------+----------------+-------+
| bin_offset_55        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000073]   | 4.0         | 5              | ...   |
| (3000073, 3000173]   | 4.0         | 10             | ...   |
| (3000173, 3000273]   | 0.0         | 1              | ...   |
| (3000273, 3000373]   | 2.0         | 5              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261373, 18261473] | 4.0         | 7              | ...   |
| (18261473, 18261573] | 0.0         | 2              | ...   |
| (18261573, 18261673] | 0.0         | 2              | ...   |
| (18261673, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 129,328 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000078],   (3000078, 3000178],
                 (3000178, 3000278],   (3000278, 3000378],
                 (3000378, 3000478],   (3000478, 3000578],
                 (3000578, 3000678],   (3000678, 3000778],
                 (3000778, 3000878],   (3000878, 3000978],
               ...
               (18260778, 18260878], (18260878, 18260978],
               (18260978, 18261078], (18261078, 18261178],
               (18261178, 18261278], (18261278, 18261378],
               (18261378, 18261478], (18261478, 18261578],
               (18261578, 18261678], (18261678, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_60  target_count
0  (3000018, 3000078]             1
1  (3000018, 3000078]             1
2  (3000018, 3000078]             1
3  (3000018, 3000078]             1
4  (3000018, 3000078]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_60  target_count
699995  (18261578, 18261678]             1
699996  (18261578, 18261678]             1
699997  (18261678, 18261710]             1
699998  (18261678, 18261710]             1
699999  (18261678, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_60  TT_S0  target_count starting_nt
0   (3000018, 3000078]    4.0             5     3000018
1   (3000078, 3000178]    4.0            10     3000078
2   (3000178, 3000278]    0.0             1     3000178
3   (3000278, 3000378]    2.0             5     3000278
4   (3000378, 3000478]    0.0             3     3000378
5   (3000478, 3000578]    0.0             1     3000478
6   (3000578, 3000678]    0.0             4     3000578
7   (3000678, 3000778]    0.0             4     3000678
8   (3000778, 3000878]    0.0             6     3000778
9   (3000878, 3000978]    0.0             4     3000878
10  (3000978, 3001078]    2.0             6     3000978
11  (3001078, 3001178]    0.0             2     3001078
12  (3001178, 3001278]    0.0             2     3001178
13  (3001278, 3001378]    0.0             5     3001278
14  (3001378, 3001478]    0.0             3     3001378
15  (3001478, 3001578]    4.0             9     3001478
16  (3001578, 3001678]    3.0             6     3001578
17  (3001678, 3001778]    0.0             7     3001678
18  (3001778, 3001878]    0.0             5     3001778
19  (3001878, 3001978]    0.0             1     3001878
20  (3001978, 3002078]    1.0             4     3001978
21  (3002078, 3002178]    0.0             1     3002078
22  (3002178, 3002278]    4.0             7     3002178
23  (3002278, 3002378]    9.0             3     3002278
24  (3002378, 3002478]   19.0             4     3002378
25  (3002478, 3002578]    4.0             3     3002478
26  (3002578, 3002678]    0.0             1     3002578
27  (3002678, 3002778]    0.0             3     3002678
28  (3002778, 3002878]    0.0             2     3002778
29  (3002878, 3002978]    1.0             2     3002878
30  (3002978, 3003078]    2.0             8     3002978
31  (3003078, 3003178]    0.0             0     3003078
32  (3003178, 3003278]    0.0             0     3003178
33  (3003278, 3003378]    1.0             9     3003278
34  (3003378, 3003478]    0.0             1     3003378
35  (3003478, 3003578]    0.0             3     3003478
36  (3003578, 3003678]    1.0             2     3003578
37  (3003678, 3003778]    4.0             8     3003678
38  (3003778, 3003878]    0.0             1     3003778
39  (3003878, 3003978]    8.0             9     3003878
40  (3003978, 3004078]    0.0             0     3003978
41  (3004078, 3004178]    0.0             0     3004078
42  (3004178, 3004278]    3.0             5     3004178
43  (3004278, 3004378]    2.0             3     3004278
44  (3004378, 3004478]    0.0             0     3004378
45  (3004478, 3004578]    0.0             6     3004478
46  (3004578, 3004678]    1.0             2     3004578
47  (3004678, 3004778]    0.0             0     3004678
48  (3004778, 3004878]   10.0             6     3004778
49  (3004878, 3004978]    3.0             3     3004878
(152618, 4)
bin_offset_60    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         4.0      0            0      0     0
1         4.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613    4.0      0            0      0     0
152614    4.0      0            0      0     0
152615    0.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         4.0             0                   0             0            0
1         4.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613    4.0             0                   0             0            0
152614    4.0             0                   0             0            0
152615    0.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.10518418535166232
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 218597.0
cluster target count 572142
!!cluster density 0.38206773842857195
cluster signal 238314.0
cluster target count 127858
!!cluster density 1.8638958844968636

Labels mapping
 {0: 0, 1: 1}
DEBUG: 136565 16053

 +----------------------+-------------+----------------+-------+
| bin_offset_60        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000078]   | 4.0         | 5              | ...   |
| (3000078, 3000178]   | 4.0         | 10             | ...   |
| (3000178, 3000278]   | 0.0         | 1              | ...   |
| (3000278, 3000378]   | 2.0         | 5              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261378, 18261478] | 4.0         | 6              | ...   |
| (18261478, 18261578] | 0.0         | 2              | ...   |
| (18261578, 18261678] | 0.0         | 2              | ...   |
| (18261678, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 136,565 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000083],   (3000083, 3000183],
                 (3000183, 3000283],   (3000283, 3000383],
                 (3000383, 3000483],   (3000483, 3000583],
                 (3000583, 3000683],   (3000683, 3000783],
                 (3000783, 3000883],   (3000883, 3000983],
               ...
               (18260783, 18260883], (18260883, 18260983],
               (18260983, 18261083], (18261083, 18261183],
               (18261183, 18261283], (18261283, 18261383],
               (18261383, 18261483], (18261483, 18261583],
               (18261583, 18261683], (18261683, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_65  target_count
0  (3000018, 3000083]             1
1  (3000018, 3000083]             1
2  (3000018, 3000083]             1
3  (3000018, 3000083]             1
4  (3000018, 3000083]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_65  target_count
699995  (18261583, 18261683]             1
699996  (18261583, 18261683]             1
699997  (18261583, 18261683]             1
699998  (18261683, 18261710]             1
699999  (18261683, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_65  TT_S0  target_count starting_nt
0   (3000018, 3000083]    4.0             5     3000018
1   (3000083, 3000183]    4.0            10     3000083
2   (3000183, 3000283]    0.0             1     3000183
3   (3000283, 3000383]    2.0             5     3000283
4   (3000383, 3000483]    0.0             3     3000383
5   (3000483, 3000583]    0.0             1     3000483
6   (3000583, 3000683]    0.0             4     3000583
7   (3000683, 3000783]    0.0             4     3000683
8   (3000783, 3000883]    0.0             6     3000783
9   (3000883, 3000983]    0.0             4     3000883
10  (3000983, 3001083]    2.0             6     3000983
11  (3001083, 3001183]    0.0             2     3001083
12  (3001183, 3001283]    0.0             2     3001183
13  (3001283, 3001383]    0.0             5     3001283
14  (3001383, 3001483]    0.0             3     3001383
15  (3001483, 3001583]    4.0             9     3001483
16  (3001583, 3001683]    3.0             7     3001583
17  (3001683, 3001783]    0.0             7     3001683
18  (3001783, 3001883]    0.0             4     3001783
19  (3001883, 3001983]    0.0             2     3001883
20  (3001983, 3002083]    1.0             3     3001983
21  (3002083, 3002183]    0.0             1     3002083
22  (3002183, 3002283]    4.0             7     3002183
23  (3002283, 3002383]    9.0             3     3002283
24  (3002383, 3002483]   19.0             4     3002383
25  (3002483, 3002583]    4.0             3     3002483
26  (3002583, 3002683]    0.0             1     3002583
27  (3002683, 3002783]    0.0             3     3002683
28  (3002783, 3002883]    0.0             2     3002783
29  (3002883, 3002983]    1.0             3     3002883
30  (3002983, 3003083]    2.0             7     3002983
31  (3003083, 3003183]    0.0             0     3003083
32  (3003183, 3003283]    0.0             0     3003183
33  (3003283, 3003383]    1.0             9     3003283
34  (3003383, 3003483]    0.0             1     3003383
35  (3003483, 3003583]    0.0             3     3003483
36  (3003583, 3003683]    2.0             3     3003583
37  (3003683, 3003783]    3.0             7     3003683
38  (3003783, 3003883]    0.0             1     3003783
39  (3003883, 3003983]    8.0             9     3003883
40  (3003983, 3004083]    0.0             0     3003983
41  (3004083, 3004183]    0.0             0     3004083
42  (3004183, 3004283]    3.0             5     3004183
43  (3004283, 3004383]    2.0             3     3004283
44  (3004383, 3004483]    0.0             0     3004383
45  (3004483, 3004583]    0.0             6     3004483
46  (3004583, 3004683]    1.0             2     3004583
47  (3004683, 3004783]    0.0             0     3004683
48  (3004783, 3004883]   10.0             7     3004783
49  (3004883, 3004983]    3.0             2     3004883
(152618, 4)
bin_offset_65    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         4.0      0            0      0     0
1         4.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613    4.0      0            0      0     0
152614    4.0      0            0      0     0
152615    0.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         4.0             0                   0             0            0
1         4.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613    4.0             0                   0             0            0
152614    4.0             0                   0             0            0
152615    0.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.8475671283859046
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 1 0 0 1 1 1 1 0 1
 1 1 1 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1]
threshold density 1.30546
cluster signal 165103.0
cluster target count 525349
!!cluster density 0.31427298805175224
cluster signal 291808.0
cluster target count 174651
!!cluster density 1.6708063509513258

Labels mapping
 {1: 0, 0: 1}
DEBUG: 129354 23264

 +----------------------+-------------+----------------+-------+
| bin_offset_65        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000083]   | 4.0         | 5              | ...   |
| (3000083, 3000183]   | 4.0         | 10             | ...   |
| (3000183, 3000283]   | 0.0         | 1              | ...   |
| (3000283, 3000383]   | 2.0         | 5              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261383, 18261483] | 4.0         | 5              | ...   |
| (18261483, 18261583] | 0.0         | 2              | ...   |
| (18261583, 18261683] | 0.0         | 3              | ...   |
| (18261683, 18261710] | 4.0         | 2              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 129,354 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000088],   (3000088, 3000188],
                 (3000188, 3000288],   (3000288, 3000388],
                 (3000388, 3000488],   (3000488, 3000588],
                 (3000588, 3000688],   (3000688, 3000788],
                 (3000788, 3000888],   (3000888, 3000988],
               ...
               (18260788, 18260888], (18260888, 18260988],
               (18260988, 18261088], (18261088, 18261188],
               (18261188, 18261288], (18261288, 18261388],
               (18261388, 18261488], (18261488, 18261588],
               (18261588, 18261688], (18261688, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_70  target_count
0  (3000018, 3000088]             1
1  (3000018, 3000088]             1
2  (3000018, 3000088]             1
3  (3000018, 3000088]             1
4  (3000018, 3000088]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_70  target_count
699995  (18261588, 18261688]             1
699996  (18261588, 18261688]             1
699997  (18261588, 18261688]             1
699998  (18261688, 18261710]             1
699999  (18261688, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_70  TT_S0  target_count starting_nt
0   (3000018, 3000088]    7.0             8     3000018
1   (3000088, 3000188]    1.0             7     3000088
2   (3000188, 3000288]    0.0             1     3000188
3   (3000288, 3000388]    2.0             7     3000288
4   (3000388, 3000488]    0.0             1     3000388
5   (3000488, 3000588]    0.0             1     3000488
6   (3000588, 3000688]    0.0             5     3000588
7   (3000688, 3000788]    0.0             5     3000688
8   (3000788, 3000888]    0.0             5     3000788
9   (3000888, 3000988]    0.0             3     3000888
10  (3000988, 3001088]    2.0             6     3000988
11  (3001088, 3001188]    0.0             3     3001088
12  (3001188, 3001288]    0.0             1     3001188
13  (3001288, 3001388]    0.0             5     3001288
14  (3001388, 3001488]    0.0             4     3001388
15  (3001488, 3001588]    4.0             8     3001488
16  (3001588, 3001688]    3.0             7     3001588
17  (3001688, 3001788]    0.0             7     3001688
18  (3001788, 3001888]    0.0             4     3001788
19  (3001888, 3001988]    0.0             2     3001888
20  (3001988, 3002088]    1.0             3     3001988
21  (3002088, 3002188]    0.0             1     3002088
22  (3002188, 3002288]    4.0             7     3002188
23  (3002288, 3002388]    9.0             3     3002288
24  (3002388, 3002488]   19.0             4     3002388
25  (3002488, 3002588]    4.0             3     3002488
26  (3002588, 3002688]    0.0             1     3002588
27  (3002688, 3002788]    0.0             3     3002688
28  (3002788, 3002888]    0.0             2     3002788
29  (3002888, 3002988]    1.0             4     3002888
30  (3002988, 3003088]    2.0             6     3002988
31  (3003088, 3003188]    0.0             0     3003088
32  (3003188, 3003288]    0.0             0     3003188
33  (3003288, 3003388]    1.0             9     3003288
34  (3003388, 3003488]    0.0             1     3003388
35  (3003488, 3003588]    1.0             4     3003488
36  (3003588, 3003688]    1.0             3     3003588
37  (3003688, 3003788]    3.0             6     3003688
38  (3003788, 3003888]    0.0             1     3003788
39  (3003888, 3003988]    8.0             9     3003888
40  (3003988, 3004088]    0.0             0     3003988
41  (3004088, 3004188]    0.0             0     3004088
42  (3004188, 3004288]    3.0             5     3004188
43  (3004288, 3004388]    2.0             3     3004288
44  (3004388, 3004488]    0.0             0     3004388
45  (3004488, 3004588]    0.0             6     3004488
46  (3004588, 3004688]    1.0             2     3004588
47  (3004688, 3004788]    0.0             0     3004688
48  (3004788, 3004888]   10.0             7     3004788
49  (3004888, 3004988]    3.0             2     3004888
(152618, 4)
bin_offset_70    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         7.0      0            0      0     0
1         1.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613    4.0      0            0      0     0
152614    4.0      0            0      0     0
152615    0.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         7.0             0                   0             0            0
1         1.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613    4.0             0                   0             0            0
152614    4.0             0                   0             0            0
152615    0.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
6.5523070673184025e-06
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 456419.0
cluster target count 699993
!!cluster density 0.6520336631937748
cluster signal 492.0
cluster target count 7
!!cluster density 70.28571428571429

Labels mapping
 {0: 0, 1: 1}
DEBUG: 152617 1

 +----------------------+-------------+----------------+-------+
| bin_offset_70        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000088]   | 7.0         | 8              | ...   |
| (3000088, 3000188]   | 1.0         | 7              | ...   |
| (3000188, 3000288]   | 0.0         | 1              | ...   |
| (3000288, 3000388]   | 2.0         | 7              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261388, 18261488] | 4.0         | 6              | ...   |
| (18261488, 18261588] | 0.0         | 1              | ...   |
| (18261588, 18261688] | 0.0         | 3              | ...   |
| (18261688, 18261710] | 4.0         | 2              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 152,617 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000093],   (3000093, 3000193],
                 (3000193, 3000293],   (3000293, 3000393],
                 (3000393, 3000493],   (3000493, 3000593],
                 (3000593, 3000693],   (3000693, 3000793],
                 (3000793, 3000893],   (3000893, 3000993],
               ...
               (18260793, 18260893], (18260893, 18260993],
               (18260993, 18261093], (18261093, 18261193],
               (18261193, 18261293], (18261293, 18261393],
               (18261393, 18261493], (18261493, 18261593],
               (18261593, 18261693], (18261693, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_75  target_count
0  (3000018, 3000093]             1
1  (3000018, 3000093]             1
2  (3000018, 3000093]             1
3  (3000018, 3000093]             1
4  (3000018, 3000093]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_75  target_count
699995  (18261593, 18261693]             1
699996  (18261593, 18261693]             1
699997  (18261593, 18261693]             1
699998  (18261693, 18261710]             1
699999  (18261693, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_75  TT_S0  target_count starting_nt
0   (3000018, 3000093]    7.0             9     3000018
1   (3000093, 3000193]    1.0             6     3000093
2   (3000193, 3000293]    0.0             1     3000193
3   (3000293, 3000393]    2.0             7     3000293
4   (3000393, 3000493]    0.0             1     3000393
5   (3000493, 3000593]    0.0             1     3000493
6   (3000593, 3000693]    0.0             6     3000593
7   (3000693, 3000793]    0.0             4     3000693
8   (3000793, 3000893]    0.0             6     3000793
9   (3000893, 3000993]    0.0             2     3000893
10  (3000993, 3001093]    2.0             6     3000993
11  (3001093, 3001193]    0.0             3     3001093
12  (3001193, 3001293]    0.0             2     3001193
13  (3001293, 3001393]    0.0             5     3001293
14  (3001393, 3001493]    0.0             3     3001393
15  (3001493, 3001593]    4.0             9     3001493
16  (3001593, 3001693]    3.0             7     3001593
17  (3001693, 3001793]    0.0             7     3001693
18  (3001793, 3001893]    0.0             3     3001793
19  (3001893, 3001993]    0.0             2     3001893
20  (3001993, 3002093]    1.0             3     3001993
21  (3002093, 3002193]    0.0             2     3002093
22  (3002193, 3002293]    4.0             6     3002193
23  (3002293, 3002393]    9.0             3     3002293
24  (3002393, 3002493]   19.0             5     3002393
25  (3002493, 3002593]    4.0             2     3002493
26  (3002593, 3002693]    0.0             2     3002593
27  (3002693, 3002793]    0.0             2     3002693
28  (3002793, 3002893]    0.0             2     3002793
29  (3002893, 3002993]    1.0             5     3002893
30  (3002993, 3003093]    2.0             5     3002993
31  (3003093, 3003193]    0.0             0     3003093
32  (3003193, 3003293]    0.0             0     3003193
33  (3003293, 3003393]    1.0             9     3003293
34  (3003393, 3003493]    0.0             1     3003393
35  (3003493, 3003593]    1.0             4     3003493
36  (3003593, 3003693]    1.0             3     3003593
37  (3003693, 3003793]    3.0             6     3003693
38  (3003793, 3003893]    0.0             2     3003793
39  (3003893, 3003993]    8.0             8     3003893
40  (3003993, 3004093]    0.0             0     3003993
41  (3004093, 3004193]    0.0             1     3004093
42  (3004193, 3004293]    3.0             4     3004193
43  (3004293, 3004393]    2.0             3     3004293
44  (3004393, 3004493]    0.0             1     3004393
45  (3004493, 3004593]    0.0             5     3004493
46  (3004593, 3004693]    1.0             2     3004593
47  (3004693, 3004793]    0.0             0     3004693
48  (3004793, 3004893]   10.0             7     3004793
49  (3004893, 3004993]    3.0             2     3004893
(152618, 4)
bin_offset_75    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         7.0      0            0      0     0
1         1.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613    4.0      0            0      0     0
152614    4.0      0            0      0     0
152615    0.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         7.0             0                   0             0            0
1         1.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613    4.0             0                   0             0            0
152614    4.0             0                   0             0            0
152615    0.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.1528915331088076
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 292143.0
cluster target count 175284
!!cluster density 1.6666837817484768
cluster signal 164768.0
cluster target count 524716
!!cluster density 0.3140136759694768

Labels mapping
 {1: 1, 0: 0}
DEBUG: 129284 23334

 +----------------------+-------------+----------------+-------+
| bin_offset_75        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000093, 3000193]   | 1.0         | 6              | ...   |
| (3000193, 3000293]   | 0.0         | 1              | ...   |
| (3000293, 3000393]   | 2.0         | 7              | ...   |
| (3000393, 3000493]   | 0.0         | 1              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261393, 18261493] | 4.0         | 6              | ...   |
| (18261493, 18261593] | 0.0         | 1              | ...   |
| (18261593, 18261693] | 0.0         | 3              | ...   |
| (18261693, 18261710] | 4.0         | 2              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 129,284 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000098],   (3000098, 3000198],
                 (3000198, 3000298],   (3000298, 3000398],
                 (3000398, 3000498],   (3000498, 3000598],
                 (3000598, 3000698],   (3000698, 3000798],
                 (3000798, 3000898],   (3000898, 3000998],
               ...
               (18260798, 18260898], (18260898, 18260998],
               (18260998, 18261098], (18261098, 18261198],
               (18261198, 18261298], (18261298, 18261398],
               (18261398, 18261498], (18261498, 18261598],
               (18261598, 18261698], (18261698, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_80  target_count
0  (3000018, 3000098]             1
1  (3000018, 3000098]             1
2  (3000018, 3000098]             1
3  (3000018, 3000098]             1
4  (3000018, 3000098]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_80  target_count
699995  (18261598, 18261698]             1
699996  (18261598, 18261698]             1
699997  (18261598, 18261698]             1
699998  (18261698, 18261710]             1
699999  (18261698, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_80  TT_S0  target_count starting_nt
0   (3000018, 3000098]    7.0            10     3000018
1   (3000098, 3000198]    1.0             5     3000098
2   (3000198, 3000298]    0.0             1     3000198
3   (3000298, 3000398]    2.0             7     3000298
4   (3000398, 3000498]    0.0             1     3000398
5   (3000498, 3000598]    0.0             1     3000498
6   (3000598, 3000698]    0.0             6     3000598
7   (3000698, 3000798]    0.0             5     3000698
8   (3000798, 3000898]    0.0             5     3000798
9   (3000898, 3000998]    0.0             2     3000898
10  (3000998, 3001098]    2.0             7     3000998
11  (3001098, 3001198]    0.0             2     3001098
12  (3001198, 3001298]    0.0             2     3001198
13  (3001298, 3001398]    0.0             5     3001298
14  (3001398, 3001498]    0.0             3     3001398
15  (3001498, 3001598]    4.0            10     3001498
16  (3001598, 3001698]    3.0             6     3001598
17  (3001698, 3001798]    0.0             7     3001698
18  (3001798, 3001898]    0.0             3     3001798
19  (3001898, 3001998]    0.0             2     3001898
20  (3001998, 3002098]    1.0             3     3001998
21  (3002098, 3002198]    0.0             2     3002098
22  (3002198, 3002298]   11.0             7     3002198
23  (3002298, 3002398]    2.0             2     3002298
24  (3002398, 3002498]   19.0             5     3002398
25  (3002498, 3002598]    4.0             2     3002498
26  (3002598, 3002698]    0.0             2     3002598
27  (3002698, 3002798]    0.0             2     3002698
28  (3002798, 3002898]    0.0             2     3002798
29  (3002898, 3002998]    1.0             5     3002898
30  (3002998, 3003098]    2.0             5     3002998
31  (3003098, 3003198]    0.0             0     3003098
32  (3003198, 3003298]    0.0             0     3003198
33  (3003298, 3003398]    1.0             9     3003298
34  (3003398, 3003498]    0.0             1     3003398
35  (3003498, 3003598]    1.0             4     3003498
36  (3003598, 3003698]    1.0             3     3003598
37  (3003698, 3003798]    3.0             6     3003698
38  (3003798, 3003898]    0.0             2     3003798
39  (3003898, 3003998]    8.0             8     3003898
40  (3003998, 3004098]    0.0             0     3003998
41  (3004098, 3004198]    0.0             1     3004098
42  (3004198, 3004298]    3.0             5     3004198
43  (3004298, 3004398]    2.0             2     3004298
44  (3004398, 3004498]    0.0             1     3004398
45  (3004498, 3004598]    0.0             6     3004498
46  (3004598, 3004698]    1.0             1     3004598
47  (3004698, 3004798]    0.0             0     3004698
48  (3004798, 3004898]   10.0             7     3004798
49  (3004898, 3004998]    3.0             2     3004898
(152618, 4)
bin_offset_80    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         7.0      0            0      0     0
1         1.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613    3.0      0            0      0     0
152614    4.0      0            0      0     0
152615    0.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         7.0             0                   0             0            0
1         1.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613    3.0             0                   0             0            0
152614    4.0             0                   0             0            0
152615    0.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.15293739925827884
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 292139.0
cluster target count 175344
!!cluster density 1.6660906560817592
cluster signal 164772.0
cluster target count 524656
!!cluster density 0.31405721082004207

Labels mapping
 {1: 1, 0: 0}
DEBUG: 129277 23341

 +----------------------+-------------+----------------+-------+
| bin_offset_80        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000098, 3000198]   | 1.0         | 5              | ...   |
| (3000198, 3000298]   | 0.0         | 1              | ...   |
| (3000298, 3000398]   | 2.0         | 7              | ...   |
| (3000398, 3000498]   | 0.0         | 1              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261398, 18261498] | 4.0         | 5              | ...   |
| (18261498, 18261598] | 0.0         | 1              | ...   |
| (18261598, 18261698] | 0.0         | 3              | ...   |
| (18261698, 18261710] | 4.0         | 2              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 129,277 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000103],   (3000103, 3000203],
                 (3000203, 3000303],   (3000303, 3000403],
                 (3000403, 3000503],   (3000503, 3000603],
                 (3000603, 3000703],   (3000703, 3000803],
                 (3000803, 3000903],   (3000903, 3001003],
               ...
               (18260803, 18260903], (18260903, 18261003],
               (18261003, 18261103], (18261103, 18261203],
               (18261203, 18261303], (18261303, 18261403],
               (18261403, 18261503], (18261503, 18261603],
               (18261603, 18261703], (18261703, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_85  target_count
0  (3000018, 3000103]             1
1  (3000018, 3000103]             1
2  (3000018, 3000103]             1
3  (3000018, 3000103]             1
4  (3000018, 3000103]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_85  target_count
699995  (18261603, 18261703]             1
699996  (18261603, 18261703]             1
699997  (18261603, 18261703]             1
699998  (18261603, 18261703]             1
699999  (18261703, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_85  TT_S0  target_count starting_nt
0   (3000018, 3000103]    7.0            11     3000018
1   (3000103, 3000203]    1.0             4     3000103
2   (3000203, 3000303]    0.0             1     3000203
3   (3000303, 3000403]    2.0             7     3000303
4   (3000403, 3000503]    0.0             1     3000403
5   (3000503, 3000603]    0.0             1     3000503
6   (3000603, 3000703]    0.0             6     3000603
7   (3000703, 3000803]    0.0             5     3000703
8   (3000803, 3000903]    0.0             5     3000803
9   (3000903, 3001003]    0.0             3     3000903
10  (3001003, 3001103]    2.0             6     3001003
11  (3001103, 3001203]    0.0             2     3001103
12  (3001203, 3001303]    0.0             3     3001203
13  (3001303, 3001403]    0.0             4     3001303
14  (3001403, 3001503]    1.0             4     3001403
15  (3001503, 3001603]    3.0             9     3001503
16  (3001603, 3001703]    3.0             6     3001603
17  (3001703, 3001803]    0.0             8     3001703
18  (3001803, 3001903]    0.0             2     3001803
19  (3001903, 3002003]    0.0             2     3001903
20  (3002003, 3002103]    1.0             3     3002003
21  (3002103, 3002203]    0.0             2     3002103
22  (3002203, 3002303]   11.0             7     3002203
23  (3002303, 3002403]    2.0             2     3002303
24  (3002403, 3002503]   19.0             5     3002403
25  (3002503, 3002603]    4.0             2     3002503
26  (3002603, 3002703]    0.0             3     3002603
27  (3002703, 3002803]    0.0             1     3002703
28  (3002803, 3002903]    0.0             2     3002803
29  (3002903, 3003003]    1.0             5     3002903
30  (3003003, 3003103]    2.0             5     3003003
31  (3003103, 3003203]    0.0             0     3003103
32  (3003203, 3003303]    0.0             0     3003203
33  (3003303, 3003403]    1.0             9     3003303
34  (3003403, 3003503]    0.0             2     3003403
35  (3003503, 3003603]    1.0             3     3003503
36  (3003603, 3003703]    1.0             3     3003603
37  (3003703, 3003803]    3.0             6     3003703
38  (3003803, 3003903]    0.0             3     3003803
39  (3003903, 3004003]    8.0             7     3003903
40  (3004003, 3004103]    0.0             0     3004003
41  (3004103, 3004203]    0.0             1     3004103
42  (3004203, 3004303]    5.0             6     3004203
43  (3004303, 3004403]    0.0             1     3004303
44  (3004403, 3004503]    0.0             1     3004403
45  (3004503, 3004603]    1.0             7     3004503
46  (3004603, 3004703]    0.0             0     3004603
47  (3004703, 3004803]    0.0             0     3004703
48  (3004803, 3004903]   10.0             7     3004803
49  (3004903, 3005003]    3.0             2     3004903
(152618, 4)
bin_offset_85    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         7.0      0            0      0     0
1         1.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613    3.0      0            0      0     0
152614    4.0      0            0      0     0
152615    0.0      0            0      0     0
152616    4.0      0            0      0     0
152617    0.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         7.0             0                   0             0            0
1         1.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613    3.0             0                   0             0            0
152614    4.0             0                   0             0            0
152615    0.0             0                   0             0            0
152616    4.0             0                   0             0            0
152617    0.0             0                   0             0            0

[152618 rows x 5 columns]
0.8466104915540762
[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 0 0 0 0 1 0 0 0 1 0 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0
 1 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1]
threshold density 1.30546
cluster signal 292587.0
cluster target count 175877
!!cluster density 1.6635887580525026
cluster signal 164324.0
cluster target count 524123
!!cluster density 0.31352182598359546

Labels mapping
 {0: 1, 1: 0}
DEBUG: 129208 23410

 +----------------------+-------------+----------------+-------+
| bin_offset_85        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000103, 3000203]   | 1.0         | 4              | ...   |
| (3000203, 3000303]   | 0.0         | 1              | ...   |
| (3000303, 3000403]   | 2.0         | 7              | ...   |
| (3000403, 3000503]   | 0.0         | 1              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261403, 18261503] | 4.0         | 4              | ...   |
| (18261503, 18261603] | 0.0         | 1              | ...   |
| (18261603, 18261703] | 4.0         | 4              | ...   |
| (18261703, 18261710] | 0.0         | 1              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 129,208 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000108],   (3000108, 3000208],
                 (3000208, 3000308],   (3000308, 3000408],
                 (3000408, 3000508],   (3000508, 3000608],
                 (3000608, 3000708],   (3000708, 3000808],
                 (3000808, 3000908],   (3000908, 3001008],
               ...
               (18260808, 18260908], (18260908, 18261008],
               (18261008, 18261108], (18261108, 18261208],
               (18261208, 18261308], (18261308, 18261408],
               (18261408, 18261508], (18261508, 18261608],
               (18261608, 18261708], (18261708, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_90  target_count
0  (3000018, 3000108]             1
1  (3000018, 3000108]             1
2  (3000018, 3000108]             1
3  (3000018, 3000108]             1
4  (3000018, 3000108]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_90  target_count
699995  (18261608, 18261708]             1
699996  (18261608, 18261708]             1
699997  (18261608, 18261708]             1
699998  (18261608, 18261708]             1
699999  (18261708, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_90  TT_S0  target_count starting_nt
0   (3000018, 3000108]    7.0            11     3000018
1   (3000108, 3000208]    1.0             4     3000108
2   (3000208, 3000308]    0.0             1     3000208
3   (3000308, 3000408]    2.0             7     3000308
4   (3000408, 3000508]    0.0             1     3000408
5   (3000508, 3000608]    0.0             2     3000508
6   (3000608, 3000708]    0.0             5     3000608
7   (3000708, 3000808]    0.0             6     3000708
8   (3000808, 3000908]    0.0             4     3000808
9   (3000908, 3001008]    0.0             3     3000908
10  (3001008, 3001108]    2.0             6     3001008
11  (3001108, 3001208]    0.0             2     3001108
12  (3001208, 3001308]    0.0             3     3001208
13  (3001308, 3001408]    0.0             4     3001308
14  (3001408, 3001508]    1.0             4     3001408
15  (3001508, 3001608]    3.0             9     3001508
16  (3001608, 3001708]    3.0             6     3001608
17  (3001708, 3001808]    0.0             8     3001708
18  (3001808, 3001908]    0.0             2     3001808
19  (3001908, 3002008]    1.0             3     3001908
20  (3002008, 3002108]    0.0             2     3002008
21  (3002108, 3002208]    0.0             2     3002108
22  (3002208, 3002308]   11.0             7     3002208
23  (3002308, 3002408]    2.0             2     3002308
24  (3002408, 3002508]   19.0             5     3002408
25  (3002508, 3002608]    4.0             2     3002508
26  (3002608, 3002708]    0.0             3     3002608
27  (3002708, 3002808]    0.0             1     3002708
28  (3002808, 3002908]    0.0             2     3002808
29  (3002908, 3003008]    1.0             5     3002908
30  (3003008, 3003108]    2.0             5     3003008
31  (3003108, 3003208]    0.0             0     3003108
32  (3003208, 3003308]    0.0             1     3003208
33  (3003308, 3003408]    1.0             8     3003308
34  (3003408, 3003508]    0.0             3     3003408
35  (3003508, 3003608]    1.0             2     3003508
36  (3003608, 3003708]    1.0             3     3003608
37  (3003708, 3003808]    3.0             6     3003708
38  (3003808, 3003908]    0.0             3     3003808
39  (3003908, 3004008]    8.0             7     3003908
40  (3004008, 3004108]    0.0             0     3004008
41  (3004108, 3004208]    0.0             1     3004108
42  (3004208, 3004308]    5.0             6     3004208
43  (3004308, 3004408]    0.0             1     3004308
44  (3004408, 3004508]    0.0             1     3004408
45  (3004508, 3004608]    1.0             7     3004508
46  (3004608, 3004708]    0.0             0     3004608
47  (3004708, 3004808]    0.0             1     3004708
48  (3004808, 3004908]   10.0             6     3004808
49  (3004908, 3005008]    3.0             2     3004908
(152618, 4)
bin_offset_90    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         7.0      0            0      0     0
1         1.0      0            0      0     0
2         0.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613    3.0      0            0      0     0
152614    4.0      0            0      0     0
152615    0.0      0            0      0     0
152616    4.0      0            0      0     0
152617    0.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         7.0             0                   0             0            0
1         1.0             0                   0             0            0
2         0.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613    3.0             0                   0             0            0
152614    4.0             0                   0             0            0
152615    0.0             0                   0             0            0
152616    4.0             0                   0             0            0
152617    0.0             0                   0             0            0

[152618 rows x 5 columns]
0.1261515679670812
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 193427.0
cluster target count 550844
!!cluster density 0.3511466041202228
cluster signal 263484.0
cluster target count 149156
!!cluster density 1.7664995038751374

Labels mapping
 {0: 0, 1: 1}
DEBUG: 133365 19253

 +----------------------+-------------+----------------+-------+
| bin_offset_90        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000108]   | 7.0         | 11             | ...   |
| (3000108, 3000208]   | 1.0         | 4              | ...   |
| (3000208, 3000308]   | 0.0         | 1              | ...   |
| (3000308, 3000408]   | 2.0         | 7              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261408, 18261508] | 4.0         | 4              | ...   |
| (18261508, 18261608] | 0.0         | 1              | ...   |
| (18261608, 18261708] | 4.0         | 4              | ...   |
| (18261708, 18261710] | 0.0         | 1              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 133,365 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000113],   (3000113, 3000213],
                 (3000213, 3000313],   (3000313, 3000413],
                 (3000413, 3000513],   (3000513, 3000613],
                 (3000613, 3000713],   (3000713, 3000813],
                 (3000813, 3000913],   (3000913, 3001013],
               ...
               (18260713, 18260813], (18260813, 18260913],
               (18260913, 18261013], (18261013, 18261113],
               (18261113, 18261213], (18261213, 18261313],
               (18261313, 18261413], (18261413, 18261513],
               (18261513, 18261613], (18261613, 18261710]],
              dtype='interval[int64, right]', length=152617)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

        bin_offset_95  target_count
0  (3000018, 3000113]             1
1  (3000018, 3000113]             1
2  (3000018, 3000113]             1
3  (3000018, 3000113]             1
4  (3000018, 3000113]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

               bin_offset_95  target_count
699995  (18261513, 18261613]             1
699996  (18261613, 18261710]             1
699997  (18261613, 18261710]             1
699998  (18261613, 18261710]             1
699999  (18261613, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
         bin_offset_95  TT_S0  target_count starting_nt
0   (3000018, 3000113]    7.0            11     3000018
1   (3000113, 3000213]    1.0             4     3000113
2   (3000213, 3000313]    2.0             2     3000213
3   (3000313, 3000413]    0.0             6     3000313
4   (3000413, 3000513]    0.0             1     3000413
5   (3000513, 3000613]    0.0             3     3000513
6   (3000613, 3000713]    0.0             4     3000613
7   (3000713, 3000813]    0.0             6     3000713
8   (3000813, 3000913]    0.0             4     3000813
9   (3000913, 3001013]    0.0             3     3000913
10  (3001013, 3001113]    2.0             6     3001013
11  (3001113, 3001213]    0.0             2     3001113
12  (3001213, 3001313]    0.0             3     3001213
13  (3001313, 3001413]    0.0             4     3001313
14  (3001413, 3001513]    1.0             4     3001413
15  (3001513, 3001613]    3.0            10     3001513
16  (3001613, 3001713]    3.0             6     3001613
17  (3001713, 3001813]    0.0             7     3001713
18  (3001813, 3001913]    0.0             2     3001813
19  (3001913, 3002013]    1.0             3     3001913
20  (3002013, 3002113]    0.0             2     3002013
21  (3002113, 3002213]    1.0             3     3002113
22  (3002213, 3002313]   10.0             7     3002213
23  (3002313, 3002413]    2.0             1     3002313
24  (3002413, 3002513]   19.0             5     3002413
25  (3002513, 3002613]    4.0             2     3002513
26  (3002613, 3002713]    0.0             3     3002613
27  (3002713, 3002813]    0.0             1     3002713
28  (3002813, 3002913]    0.0             2     3002813
29  (3002913, 3003013]    1.0             6     3002913
30  (3003013, 3003113]    2.0             4     3003013
31  (3003113, 3003213]    0.0             0     3003113
32  (3003213, 3003313]    0.0             1     3003213
33  (3003313, 3003413]    1.0             8     3003313
34  (3003413, 3003513]    0.0             3     3003413
35  (3003513, 3003613]    1.0             2     3003513
36  (3003613, 3003713]    1.0             3     3003613
37  (3003713, 3003813]    3.0             6     3003713
38  (3003813, 3003913]    0.0             4     3003813
39  (3003913, 3004013]    8.0             6     3003913
40  (3004013, 3004113]    0.0             0     3004013
41  (3004113, 3004213]    0.0             1     3004113
42  (3004213, 3004313]    5.0             6     3004213
43  (3004313, 3004413]    0.0             1     3004313
44  (3004413, 3004513]    0.0             1     3004413
45  (3004513, 3004613]    1.0             7     3004513
46  (3004613, 3004713]    0.0             0     3004613
47  (3004713, 3004813]    0.0             1     3004713
48  (3004813, 3004913]   10.0             7     3004813
49  (3004913, 3005013]    3.0             1     3004913
(152617, 4)
bin_offset_95    category
TT_S0             float64
target_count        int64
starting_nt      category
dtype: object
sumos ilgis: 152617
ranges ilgis: 152617
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         7.0      0            0      0     0
1         1.0      0            0      0     0
2         2.0      0            0      0     0
3         0.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152612   10.0      0            0      0     0
152613    3.0      0            0      0     0
152614    4.0      0            0      0     0
152615    0.0      0            0      0     0
152616    4.0      0            0      0     0

[152617 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         7.0             0                   0             0            0
1         1.0             0                   0             0            0
2         2.0             0                   0             0            0
3         0.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152612   10.0             0                   0             0            0
152613    3.0             0                   0             0            0
152614    4.0             0                   0             0            0
152615    0.0             0                   0             0            0
152616    4.0             0                   0             0            0

[152617 rows x 5 columns]
0.126099975756305
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
threshold density 1.30546
cluster signal 193221.0
cluster target count 550863
!!cluster density 0.35076053392585815
cluster signal 263690.0
cluster target count 149137
!!cluster density 1.7681058355740025

Labels mapping
 {0: 0, 1: 1}
DEBUG: 133372 19245

 +----------------------+-------------+----------------+-------+
| bin_offset_95        | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000113]   | 7.0         | 11             | ...   |
| (3000113, 3000213]   | 1.0         | 4              | ...   |
| (3000213, 3000313]   | 2.0         | 2              | ...   |
| (3000313, 3000413]   | 0.0         | 6              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261313, 18261413] | 3.0         | 15             | ...   |
| (18261413, 18261513] | 4.0         | 4              | ...   |
| (18261513, 18261613] | 0.0         | 2              | ...   |
| (18261613, 18261710] | 4.0         | 4              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 133,372 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)

/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 1 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values
/opt/anaconda3/lib/python3.12/site-packages/pyranges/methods/intersection.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  sx.loc[vc.index, 0] = vc.values

OVERLAPS +--------------+-----------+-----------+------------+------------+-------+
| Chromosome   | Start     | End       | offset_0   | offset_5   | +18   |
| (object)     | (int64)   | (int64)   | (int64)    | (int64)    | ...   |
|--------------+-----------+-----------+------------+------------+-------|
| 18           | 3000018   | 3000023   | 0          | 0          | ...   |
| 18           | 3000023   | 3000028   | 0          | 1          | ...   |
| 18           | 3000028   | 3000038   | 0          | 1          | ...   |
| 18           | 3000038   | 3000093   | 0          | 1          | ...   |
| ...          | ...       | ...       | ...        | ...        | ...   |
| 18           | 18261353  | 18261358  | 0          | 0          | ...   |
| 18           | 18261358  | 18261363  | 0          | 0          | ...   |
| 18           | 18261363  | 18261368  | 0          | 0          | ...   |
| 18           | 18261368  | 18261373  | 0          | 0          | ...   |
+--------------+-----------+-----------+------------+------------+-------+
Unstranded PyRanges object has 534,677 rows and 23 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
18 hidden columns: offset_10, offset_15, offset_20, offset_25, offset_30, offset_35, ... (+ 12 more.)
OVERLAPS FILTERED +--------------+-----------+-----------+
| Chromosome   | Start     | End       |
| (category)   | (int64)   | (int64)   |
|--------------+-----------+-----------|
| 18           | 3002263   | 3002503   |
| 18           | 3003953   | 3003983   |
| 18           | 3004808   | 3004898   |
| 18           | 3005068   | 3005348   |
| ...          | ...       | ...       |
| 18           | 18247898  | 18247983  |
| 18           | 18249543  | 18249633  |
| 18           | 18250953  | 18251038  |
| 18           | 18261233  | 18261323  |
+--------------+-----------+-----------+
Unstranded PyRanges object has 14,519 rows and 3 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [3]:
print(evaluation)

count                        13302.0
mean                      128.670501
std                       113.512934
min                              5.0
25%                             80.0
50%                             95.0
75%                            140.0
max                           1985.0
mode                            95.0
ATACseq_overlap             0.791289
ATACseq_ranges_overlap      0.034008
ATACseq_Jaccard             0.033706
DNAseq_overlap              0.699477
DNAseq_ranges_overlap       0.049429
DNAseq_Jaccard              0.048401
genes_overlap               0.596375
percentage_open             0.093725
percentage_open_adj         0.112148
model_name                   k-means
Name: Length, dtype: object

In [5]:
print(evaluation)

count                        14519.0
mean                      124.223431
std                       114.045787
min                              5.0
25%                             70.0
50%                             90.0
75%                            135.0
max                           1980.0
mode                            90.0
ATACseq_overlap             0.793681
ATACseq_ranges_overlap      0.032371
ATACseq_Jaccard             0.032101
DNAseq_overlap              0.707587
DNAseq_ranges_overlap       0.047451
DNAseq_Jaccard              0.046538
genes_overlap                0.59436
percentage_open             0.098764
percentage_open_adj         0.118178
model_name                   k-means
Name: Length, dtype: object

In [7]:
import os
os.environ['COLUMNS']="300"

result = evaluator.evaluate(merged_ranges = chromatin_algos.algo5d_aggregated(1, n_clusters=10))

KeyboardInterrupt:

Exception ignored in: 'pyreadr.librdata._handle_column'
Traceback (most recent call last):
  File "pyreadr/librdata.pyx", line 229, in pyreadr.librdata.Parser._Parser__handle_column
  File "/opt/anaconda3/lib/python3.12/enum.py", line 726, in __call__
    def __call__(cls, value, names=_not_given, *values, module=None, qualname=None, type=None, start=1, boundary=None):

KeyboardInterrupt:

HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1
0       19  3000017  3000017  19_3000017    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0
4       18  3000040  3000040  18_3000040    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1        bin_offset_0  \
0       19  3000017  3000017  19_3000017    0.0    0.0  (3000016, 3000116]
1       18  3000019  3000019  18_3000019    0.0    0.0  (3000016, 3000116]
2       18  3000023  3000023  18_3000023    0.0    0.0  (3000016, 3000116]
3       18  3000025  3000025  18_3000025    0.0    0.0  (3000016, 3000116]
4       18  3000040  3000040  18_3000040    0.0    0.0  (3000016, 3000116]

   target_count
0             1
1             1
2             1
3             1
4             1
TAIL with BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  \
699995       18  9717555  9717555  18_9717555    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0

              bin_offset_0  target_count
699995  (9717516, 9717593]             1
699996  (9717516, 9717593]             1
699997  (9717516, 9717593]             1
699998  (9717516, 9717593]             1
699999  (9717516, 9717593]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

KeyError: "['TT_S2'] not found in axis"

In [3]:
import generate_consensus

ranges = generate_consensus.generate_consensus_5x20(chromatin_algos.algo5d_aggregated, [1, 2, 3])
result = evaluator.evaluate(merged_ranges = ranges)
print(result)

HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0
BINS  IntervalIndex([  (3000018, 3000018],   (3000018, 3000118],
                 (3000118, 3000218],   (3000218, 3000318],
                 (3000318, 3000418],   (3000418, 3000518],
                 (3000518, 3000618],   (3000618, 3000718],
                 (3000718, 3000818],   (3000818, 3000918],
               ...
               (18260718, 18260818], (18260818, 18260918],
               (18260918, 18261018], (18261018, 18261118],
               (18261118, 18261218], (18261218, 18261318],
               (18261318, 18261418], (18261418, 18261518],
               (18261518, 18261618], (18261618, 18261710]],
              dtype='interval[int64, right]', length=152618)
HEAD with BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       18  3000019  3000019  18_3000019    0.0    0.0    0.0
1       18  3000023  3000023  18_3000023    0.0    0.0    0.0
2       18  3000025  3000025  18_3000025    0.0    0.0    0.0
3       18  3000040  3000040  18_3000040    4.0    0.0    0.0
4       18  3000066  3000066  18_3000066    0.0    0.0    0.0

         bin_offset_0  target_count
0  (3000018, 3000118]             1
1  (3000018, 3000118]             1
2  (3000018, 3000118]             1
3  (3000018, 3000118]             1
4  (3000018, 3000118]             1
TAIL with BINS
       seqnames     start       end        CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  18261611  18261611  18_18261611    0.0    0.0    0.0
699996       18  18261615  18261615  18_18261615    0.0    0.0    0.0
699997       18  18261682  18261682  18_18261682    0.0    0.0    0.0
699998       18  18261702  18261702  18_18261702    4.0    0.0    0.0
699999       18  18261710  18261710  18_18261710    0.0    0.0    0.0

                bin_offset_0  target_count
699995  (18261518, 18261618]             1
699996  (18261518, 18261618]             1
699997  (18261618, 18261710]             1
699998  (18261618, 18261710]             1
699999  (18261618, 18261710]             1

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:137: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
          bin_offset_0  TT_S0  target_count  starting_nt
0   (3000018, 3000018]    0.0             0      3000018
1   (3000018, 3000118]    7.0            11      3000018
2   (3000118, 3000218]    1.0             4      3000118
3   (3000218, 3000318]    2.0             4      3000218
4   (3000318, 3000418]    0.0             4      3000318
5   (3000418, 3000518]    0.0             2      3000418
6   (3000518, 3000618]    0.0             2      3000518
7   (3000618, 3000718]    0.0             4      3000618
8   (3000718, 3000818]    0.0             7      3000718
9   (3000818, 3000918]    0.0             3      3000818
10  (3000918, 3001018]    0.0             3      3000918
11  (3001018, 3001118]    2.0             6      3001018
12  (3001118, 3001218]    0.0             2      3001118
13  (3001218, 3001318]    0.0             4      3001218
14  (3001318, 3001418]    0.0             3      3001318
15  (3001418, 3001518]    1.0             4      3001418
16  (3001518, 3001618]    3.0            10      3001518
17  (3001618, 3001718]    3.0             7      3001618
18  (3001718, 3001818]    0.0             6      3001718
19  (3001818, 3001918]    0.0             2      3001818
20  (3001918, 3002018]    1.0             3      3001918
21  (3002018, 3002118]    0.0             2      3002018
22  (3002118, 3002218]    1.0             4      3002118
23  (3002218, 3002318]   10.0             6      3002218
24  (3002318, 3002418]    2.0             1      3002318
25  (3002418, 3002518]   19.0             5      3002418
26  (3002518, 3002618]    4.0             2      3002518
27  (3002618, 3002718]    0.0             3      3002618
28  (3002718, 3002818]    0.0             1      3002718
29  (3002818, 3002918]    0.0             2      3002818
30  (3002918, 3003018]    1.0             6      3002918
31  (3003018, 3003118]    2.0             4      3003018
32  (3003118, 3003218]    0.0             0      3003118
33  (3003218, 3003318]    0.0             1      3003218
34  (3003318, 3003418]    1.0             8      3003318
35  (3003418, 3003518]    0.0             3      3003418
36  (3003518, 3003618]    1.0             2      3003518
37  (3003618, 3003718]    3.0             4      3003618
38  (3003718, 3003818]    1.0             6      3003718
39  (3003818, 3003918]    0.0             3      3003818
40  (3003918, 3004018]    8.0             6      3003918
41  (3004018, 3004118]    0.0             0      3004018
42  (3004118, 3004218]    0.0             1      3004118
43  (3004218, 3004318]    5.0             6      3004218
44  (3004318, 3004418]    0.0             1      3004318
45  (3004418, 3004518]    0.0             1      3004418
46  (3004518, 3004618]    1.0             7      3004518
47  (3004618, 3004718]    0.0             0      3004618
48  (3004718, 3004818]    0.0             1      3004718
49  (3004818, 3004918]   13.0             8      3004818
(152618, 4)
bin_offset_0    category
TT_S0            float64
target_count       int64
starting_nt        int64
dtype: object
sumos ilgis: 152618
ranges ilgis: 152618
Model input - NO SCALE
        TT_S0  genes  transcripts  exons  CDSs
0         0.0      0            0      0     0
1         7.0      0            0      0     0
2         1.0      0            0      0     0
3         2.0      0            0      0     0
4         0.0      0            0      0     0
...       ...    ...          ...    ...   ...
152613   10.0      0            0      0     0
152614    3.0      0            0      0     0
152615    4.0      0            0      0     0
152616    0.0      0            0      0     0
152617    4.0      0            0      0     0

[152618 rows x 5 columns]
Model input - SCALED
        TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0         0.0             0                   0             0            0
1         7.0             0                   0             0            0
2         1.0             0                   0             0            0
3         2.0             0                   0             0            0
4         0.0             0                   0             0            0
...       ...           ...                 ...           ...          ...
152613   10.0             0                   0             0            0
152614    3.0             0                   0             0            0
152615    4.0             0                   0             0            0
152616    0.0             0                   0             0            0
152617    4.0             0                   0             0            0

[152618 rows x 5 columns]
0.10474518077815198
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
threshold density 1.95819
cluster signal 219187.0
cluster target count 572145
!!cluster density 0.3830969422087058
cluster signal 237724.0
cluster target count 127855
!!cluster density 1.8593250166203903

Labels mapping
 {0: 0, 1: 0}
DEBUG: 152618 0

 +----------------------+-------------+----------------+-------+
| bin_offset_0         | TT_S0       | target_count   | +9    |
| (category)           | (float64)   | (int64)        | ...   |
|----------------------+-------------+----------------+-------|
| (3000018, 3000018]   | 0.0         | 0              | ...   |
| (3000018, 3000118]   | 7.0         | 11             | ...   |
| (3000118, 3000218]   | 1.0         | 4              | ...   |
| (3000218, 3000318]   | 2.0         | 4              | ...   |
| ...                  | ...         | ...            | ...   |
| (18261318, 18261418] | 3.0         | 15             | ...   |
| (18261418, 18261518] | 4.0         | 4              | ...   |
| (18261518, 18261618] | 0.0         | 3              | ...   |
| (18261618, 18261710] | 4.0         | 3              | ...   |
+----------------------+-------------+----------------+-------+
Unstranded PyRanges object has 152,618 rows and 12 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
9 hidden columns: starting_nt, Chromosome, Start, End, genes, transcripts, ... (+ 3 more.)
The model failed to identify open ranges.
           0
model_name

In [7]:
import pandas as pd

# Example data with a clear mode
data_with_single_mode = pd.Series([1, 2, 2, 3, 4])
print("Single Mode Example:")
print("Mode:", data_with_single_mode.mode())  # Should work fine
print("Mode:", type(data_with_single_mode.mode().iloc[0].item()))  # Should work fine

# Example data with multiple modes
data_with_multiple_modes = pd.Series([1, 2, 2, 3, 3, 4])
print("\nMultiple Modes Example:")
print("Modes:", data_with_multiple_modes.mode())
print("First Mode:", type(data_with_multiple_modes.mode().iloc[0].item()))

Single Mode Example:
Mode: 0    2
dtype: int64
Mode: <class 'int'>

Multiple Modes Example:
Modes: 0    2
1    3
dtype: int64
First Mode: <class 'int'>

In [3]:
result = evaluator.evaluate(merged_ranges = ranges)

print(result)

count                        13118.0
mean                      146.683946
std                       113.175202
min                            100.0
25%                            100.0
50%                            100.0
75%                            200.0
max                           2500.0
mode                           100.0
ATACseq_overlap             0.792635
ATACseq_ranges_overlap      0.030302
ATACseq_Jaccard             0.030064
DNAseq_overlap              0.696856
DNAseq_ranges_overlap       0.043802
DNAseq_Jaccard              0.042983
genes_overlap               0.590862
percentage_open             0.105368
percentage_open_adj          0.12608
model_name
Name: Length, dtype: object

In [3]:
import enrichment
import pyreadr

targets_df = pyreadr.read_r('../inputs/subset1.rds')[None]

print(targets_df)

       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0            19  3000017  3000017  19_3000017    0.0    0.0    0.0
1            18  3000019  3000019  18_3000019    0.0    0.0    0.0
2            18  3000023  3000023  18_3000023    0.0    0.0    0.0
3            18  3000025  3000025  18_3000025    0.0    0.0    0.0
4            18  3000040  3000040  18_3000040    4.0    0.0    0.0
...         ...      ...      ...         ...    ...    ...    ...
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

[700000 rows x 7 columns]

In [5]:
import enrichment

print(enrichment.calculate_enrichment_factors_file(ranges_filepath='../outputs/test_ranges.tsv', targets_filepath='../inputs/subset1.rds'))

/Users/lukas/VU/bio-baigiamasis/scripts/enrichment.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summed_ranges = targets_df.groupby('ranges_bin')[[SIGNAL_COLUMN, 'target_count']].sum()
/Users/lukas/VU/bio-baigiamasis/scripts/enrichment.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summed_ranges = targets_df.groupby('ranges_bin')[[SIGNAL_COLUMN, 'target_count']].sum()

Dataframe normalized signal: 0.65273
                 ranges_bin  norm_signal  pre_signal  post_signal  \
0        [3002218, 3002318)     1.428571    0.333333     2.000000
1        [3002418, 3002518)     3.800000    2.000000     2.000000
2        [3003918, 3004018)     1.333333    0.000000     0.000000
3        [3004818, 3004918)     1.625000    0.000000     0.000000
4        [3005018, 3005318)     5.666667    0.000000     1.500000
...                     ...          ...         ...          ...
13113  [18247918, 18248018)     4.333333    0.500000     0.400000
13114  [18249518, 18249618)     1.285714    1.333333     1.000000
13115  [18250918, 18251018)     1.500000    0.000000     0.142857
13116  [18251518, 18251618)     1.333333    0.200000     0.000000
13117  [18261218, 18261318)     1.111111    0.400000     0.200000

       surround_signal  enrichment_factor1  enrichment_factor2
0             2.333333            0.612245            2.188610
1             4.000000            0.950000            5.821703
2             0.000000            0.000000            2.042703
3             0.000000            0.000000            2.489544
4             1.500000            3.777778            8.681486
...                ...                 ...                 ...
13113         0.900000            4.814815            6.638784
13114         2.333333            0.551020            1.969749
13115         0.142857           10.500000            2.298041
13116         0.200000            6.666667            2.042703
13117         0.600000            1.851852            1.702252

[13118 rows x 7 columns]

/Users/lukas/VU/bio-baigiamasis/scripts/enrichment.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summed_ranges = targets_df.groupby('ranges_bin')[[SIGNAL_COLUMN, 'target_count']].sum()

In [6]:
enriched = enrichment.calculate_norm_signal(ranges, targets_df)
surround = enrichment.calculate_surround_signal(ranges, targets_df)

print(enriched)
print(surround)

/Users/lukas/VU/bio-baigiamasis/scripts/enrichment.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summed_ranges = targets_df.groupby('ranges_bin')[[SIGNAL_COLUMN, 'target_count']].sum()
/Users/lukas/VU/bio-baigiamasis/scripts/enrichment.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summed_ranges = targets_df.groupby('ranges_bin')[[SIGNAL_COLUMN, 'target_count']].sum()
/Users/lukas/VU/bio-baigiamasis/scripts/enrichment.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summed_ranges = targets_df.groupby('ranges_bin')[[SIGNAL_COLUMN, 'target_count']].sum()
/Users/lukas/VU/bio-baigiamasis/scripts/enrichment.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summed_ranges = targets_df.groupby('ranges_bin')[[SIGNAL_COLUMN, 'target_count']].sum()

KeyError: 'pre_signal'

In [4]:
ranges.df.to_csv('../outputs/test_ranges.tsv', sep='\t')

In [4]:
import enrichment

print(enrichment.get_pre_regions(ranges))
print(ranges)

+--------------+-----------+-----------+-----------+
| Chromosome   | Start     | End       | Length    |
| (category)   | (int64)   | (int64)   | (int64)   |
|--------------+-----------+-----------+-----------|
| 18           | 3005016   | 3005116   | 200       |
| 18           | 3005516   | 3005616   | 400       |
| 18           | 3010016   | 3010116   | 200       |
| 18           | 3010616   | 3010716   | 100       |
| ...          | ...       | ...       | ...       |
| 18           | 9707516   | 9707616   | 100       |
| 18           | 9707916   | 9708016   | 200       |
| 18           | 9708416   | 9708516   | 300       |
| 18           | 9708916   | 9709016   | 100       |
+--------------+-----------+-----------+-----------+
Unstranded PyRanges object has 4,985 rows and 4 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
+--------------+-----------+-----------+-----------+
| Chromosome   | Start     | End       | Length    |
| (category)   | (int64)   | (int64)   | (int64)   |
|--------------+-----------+-----------+-----------|
| 18           | 3005116   | 3005316   | 200       |
| 18           | 3005616   | 3006016   | 400       |
| 18           | 3010116   | 3010316   | 200       |
| 18           | 3010716   | 3010816   | 100       |
| ...          | ...       | ...       | ...       |
| 18           | 9707616   | 9707716   | 100       |
| 18           | 9708016   | 9708216   | 200       |
| 18           | 9708516   | 9708816   | 300       |
| 18           | 9709016   | 9709116   | 100       |
+--------------+-----------+-----------+-----------+
Unstranded PyRanges object has 4,985 rows and 4 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [5]:
import os
os.environ['COLUMNS']="300"
print(ranges)

+--------------+-----------+-----------+-----------+
| Chromosome   | Start     | End       | Length    |
| (category)   | (int64)   | (int64)   | (int64)   |
|--------------+-----------+-----------+-----------|
| 18           | 3002416   | 3002516   | 100       |
| 18           | 3005116   | 3005316   | 200       |
| 18           | 3005416   | 3005516   | 100       |
| 18           | 3005616   | 3006016   | 400       |
| ...          | ...       | ...       | ...       |
| 18           | 9708016   | 9708216   | 200       |
| 18           | 9708316   | 9708416   | 100       |
| 18           | 9708516   | 9708816   | 300       |
| 18           | 9709016   | 9709116   | 100       |
+--------------+-----------+-----------+-----------+
Unstranded PyRanges object has 6,883 rows and 4 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [6]:
test = targets_df[(targets_df["start"] >= 3010116) & (targets_df["start"] <= 3010316)]
#[3010116, 3010316]   51.0            24

print(test['target_count'].sum())
print(test['TT_S0'].sum())

24
51.0

In [31]:
import pyranges as pr

ranges.Length = ranges.End - ranges.Start
ranges_df = ranges.df
ranges_df['']

print(len(ranges[ranges.Length < 75]))
ranges2 = evaluator.process_ranges(ranges)
ranges2.Length = ranges2.End - ranges2.Start
print(len(ranges2[ranges2.Length < 75]))

1615
0

In [51]:
print(evaluator.evaluate(ranges))

count                         8182.0
mean                      182.306282
std                       197.351081
min                              5.0
25%                             80.0
50%                            115.0
75%                            210.0
max                           2085.0
ATACseq_overlap             0.751796
ATACseq_ranges_overlap      0.013469
DNAseq_overlap              0.639008
DNAseq_ranges_overlap       0.022784
genes_overlap                0.54393
percentage_open             0.153498
percentage_open_adj         0.222048
model_name
Name: Length, dtype: object

In [44]:
def calculate_gaps(pyranges_obj):
    """
    Calculate gaps between ranges in a PyRanges object.

    Parameters:
        pyranges_obj (pr.PyRanges): A PyRanges object with genomic ranges.

    Returns:
        pr.PyRanges: A PyRanges object containing the gaps.
    """
    # Convert PyRanges to a DataFrame
    df = pyranges_obj.df
    
    # Sort the ranges by Chromosome and Start position
    df = df.sort_values(["Chromosome", "Start"]).reset_index(drop=True)
    
    # Shift End and Start columns to calculate gaps
    prev_end = df.groupby("Chromosome")["End"].shift(0)   # Current End
    next_start = df.groupby("Chromosome")["Start"].shift(-1)  # Next Start
    
    # Identify gaps where End < Next Start
    gaps_df = df[(prev_end < next_start)].assign(Start=prev_end, End=next_start)[["Chromosome", "Start", "End"]]
    
    # Drop NaN rows caused by shifting and ensure integer type
    gaps_df = gaps_df.dropna().astype({"Start": "int", "End": "int"})
    
    # Convert back to PyRanges
    return pr.PyRanges(gaps_df)

In [10]:
import pandas as pd

df=pd.DataFrame(
{'Chromosome':['chr1', 'chr1', 'chr1', 'chr3'],
 'Start': [5, 20, 80, 10],
 'End':   [10, 28, 95, 38],
 'Strand':['+', '+', '-', '+'],
 'title': ['a', 'b', 'c', 'd']}
)

print(df.transpose())

               0     1     2     3
Chromosome  chr1  chr1  chr1  chr3
Start          5    20    80    10
End           10    28    95    38
Strand         +     +     -     +
title          a     b     c     d

In [49]:
import pandas as pd
import pyranges as pr

ranges_df = ranges.df
gaps = calculate_gaps(ranges)
gaps.Length = gaps.End - gaps.Start
print(len(gaps[gaps.Length <= 50]))

ranges2 = evaluator.process_ranges(ranges)
gaps2 = calculate_gaps(ranges2)
gaps2.Length = gaps2.End - gaps2.Start
print(len(gaps2[gaps2.Length <= 50]))

443
0

/var/folders/y9/8yssfmz161s4ghy99nf1f2cw0000gn/T/ipykernel_27239/19855938.py:18: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  prev_end = df.groupby("Chromosome")["End"].shift(0)   # Current End
/var/folders/y9/8yssfmz161s4ghy99nf1f2cw0000gn/T/ipykernel_27239/19855938.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  next_start = df.groupby("Chromosome")["Start"].shift(-1)  # Next Start
/var/folders/y9/8yssfmz161s4ghy99nf1f2cw0000gn/T/ipykernel_27239/19855938.py:18: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  prev_end = df.groupby("Chromosome")["End"].shift(0)   # Current End
/var/folders/y9/8yssfmz161s4ghy99nf1f2cw0000gn/T/ipykernel_27239/19855938.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  next_start = df.groupby("Chromosome")["Start"].shift(-1)  # Next Start

In [ ]:
import pandas as pd

for i in range(6):
    scale = 2 ** i
    print("Runnning scale", scale)
    evaluation = evaluator.evaluate(dataframe = chromatin_algos.algo5d(scale), model_name=f"k-means 5 features scale={scale}")
    result = pd.concat([result, evaluation], axis=1)

result.to_csv('../outputs/results1.csv', sep = '\t')

Runnning scale 1
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.17092159518882952
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 2
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.20496598538190156
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 4
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.20496598538190156
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 8
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.20496598538190156
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 16
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.20496598538190156
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 32
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.17092159518882952
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]

In [ ]:
print(result)

                         Length                      Length  \
count                    7301.0                      6456.0
mean                 188.590604                  177.850062
std                  174.998864                  157.257952
min                       100.0                       100.0
25%                       100.0                       100.0
50%                       100.0                       100.0
75%                       200.0                       200.0
max                      2400.0                      2000.0
ATACseq_overlap        0.697949                    0.668276
DNAseq_overlap         0.595329                    0.553813
genes_overlap          0.544833                    0.550809
percentage_open        0.141691                    0.118157
percentage_open_adj    0.204969                    0.170924
model_name                       k-means 5 features scale=1
min_open_signal            17.0                        19.0
max_open_signal           393.0                       393.0
min_closed_signal           0.0                         0.0
max_closed_signal          16.0                        18.0

                                         Length                      Length  \
count                                    7301.0                      7301.0
mean                                 188.590604                  188.590604
std                                  174.998864                  174.998864
min                                       100.0                       100.0
25%                                       100.0                       100.0
50%                                       100.0                       100.0
75%                                       200.0                       200.0
max                                      2400.0                      2400.0
ATACseq_overlap                        0.697949                    0.697949
DNAseq_overlap                         0.595329                    0.595329
genes_overlap                          0.544833                    0.544833
percentage_open                        0.141691                    0.141691
percentage_open_adj                    0.204969                    0.204969
model_name           k-means 5 features scale=2  k-means 5 features scale=4
min_open_signal                            17.0                        17.0
max_open_signal                           393.0                       393.0
min_closed_signal                           0.0                         0.0
max_closed_signal                          16.0                        16.0

                                         Length                       Length  \
count                                    7301.0                       7301.0
mean                                 188.590604                   188.590604
std                                  174.998864                   174.998864
min                                       100.0                        100.0
25%                                       100.0                        100.0
50%                                       100.0                        100.0
75%                                       200.0                        200.0
max                                      2400.0                       2400.0
ATACseq_overlap                        0.697949                     0.697949
DNAseq_overlap                         0.595329                     0.595329
genes_overlap                          0.544833                     0.544833
percentage_open                        0.141691                     0.141691
percentage_open_adj                    0.204969                     0.204969
model_name           k-means 5 features scale=8  k-means 5 features scale=16
min_open_signal                            17.0                         17.0
max_open_signal                           393.0                        393.0
min_closed_signal                           0.0                          0.0
max_closed_signal                          16.0                         16.0

                                          Length
count                                     6456.0
mean                                  177.850062
std                                   157.257952
min                                        100.0
25%                                        100.0
50%                                        100.0
75%                                        200.0
max                                       2000.0
ATACseq_overlap                         0.668276
DNAseq_overlap                          0.553813
genes_overlap                           0.550809
percentage_open                         0.118157
percentage_open_adj                     0.170924
model_name           k-means 5 features scale=32
min_open_signal                             19.0
max_open_signal                            393.0
min_closed_signal                            0.0
max_closed_signal                           18.0