In [1]:
import chromatin_algos
import evaluator

In [2]:
result = evaluator.evaluate(dataframe = chromatin_algos.algo5d(1))

HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.20496598538190156
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]

In [3]:
print(result)

count                      7301.0
mean                   188.590604
std                    174.998864
min                         100.0
25%                         100.0
50%                         100.0
75%                         200.0
max                        2400.0
ATACseq_overlap          0.697949
DNAseq_overlap           0.595329
genes_overlap            0.544833
percentage_open          0.141691
percentage_open_adj      0.204969
model_name
min_open_signal              17.0
max_open_signal             393.0
min_closed_signal             0.0
max_closed_signal            16.0
Name: Length, dtype: object

In [5]:
import pandas as pd

for i in range(6):
    scale = 2 ** i
    print("Runnning scale", scale)
    evaluation = evaluator.evaluate(dataframe = chromatin_algos.algo5d(scale), model_name=f"k-means 5 features scale={scale}")
    result = pd.concat([result, evaluation], axis=1)

result.to_csv('../outputs/results1.csv', sep = '\t')

Runnning scale 1
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.17092159518882952
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 2
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.20496598538190156
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 4
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.20496598538190156
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 8
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.20496598538190156
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 16
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.20496598538190156
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Runnning scale 32
HEAD
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0
BINS  IntervalIndex([(3000016, 3000016], (3000016, 3000116], (3000116, 3000216],
               (3000216, 3000316], (3000316, 3000416], (3000416, 3000516],
               (3000516, 3000616], (3000616, 3000716], (3000716, 3000816],
               (3000816, 3000916],
               ...
               (9716616, 9716716], (9716716, 9716816], (9716816, 9716916],
               (9716916, 9717016], (9717016, 9717116], (9717116, 9717216],
               (9717216, 9717316], (9717316, 9717416], (9717416, 9717516],
               (9717516, 9717593]],
              dtype='interval[int64, right]', length=67177)
HEAD w BINS
  seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
0       19  3000017  3000017  19_3000017    0.0    0.0    0.0
1       18  3000019  3000019  18_3000019    0.0    0.0    0.0
2       18  3000023  3000023  18_3000023    0.0    0.0    0.0
3       18  3000025  3000025  18_3000025    0.0    0.0    0.0
4       18  3000040  3000040  18_3000040    4.0    0.0    0.0

         bin_offset_0
0  (3000016, 3000116]
1  (3000016, 3000116]
2  (3000016, 3000116]
3  (3000016, 3000116]
4  (3000016, 3000116]
TAIL w BINS
       seqnames    start      end       CG_ID  TT_S0  TT_S1  TT_S2  \
699995       18  9717555  9717555  18_9717555    1.0    0.0    0.0
699996       19  9717571  9717571  19_9717571    0.0    0.0    0.0
699997       19  9717581  9717581  19_9717581    0.0    0.0    0.0
699998       18  9717582  9717582  18_9717582    0.0    0.0    0.0
699999       18  9717593  9717593  18_9717593    0.0    0.0    0.0

              bin_offset_0
699995  (9717516, 9717593]
699996  (9717516, 9717593]
699997  (9717516, 9717593]
699998  (9717516, 9717593]
699999  (9717516, 9717593]

/Users/lukas/VU/bio-baigiamasis/scripts/chromatin_algos.py:151: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sumos = df.groupby('bin_offset_' + str(bin_offset)).sum().reset_index()

SUMOS
    TT_S0  starting_nt
0     0.0      3000016
1     7.0      3000016
2     1.0      3000116
3     2.0      3000216
4     0.0      3000316
5     0.0      3000416
6     0.0      3000516
7     0.0      3000616
8     0.0      3000716
9     0.0      3000816
10    0.0      3000916
11    2.0      3001016
12    0.0      3001116
13    0.0      3001216
14    0.0      3001316
15    1.0      3001416
16    3.0      3001516
17    3.0      3001616
18    0.0      3001716
19    0.0      3001816
20    1.0      3001916
21    0.0      3002016
22    1.0      3002116
23   10.0      3002216
24    2.0      3002316
25   19.0      3002416
26    4.0      3002516
27    0.0      3002616
28    0.0      3002716
29    0.0      3002816
30    1.0      3002916
31    2.0      3003016
32    0.0      3003116
33    0.0      3003216
34    1.0      3003316
35    0.0      3003416
36    1.0      3003516
37    1.0      3003616
38    3.0      3003716
39    0.0      3003816
40    8.0      3003916
41    0.0      3004016
42    0.0      3004116
43    5.0      3004216
44    0.0      3004316
45    0.0      3004416
46    1.0      3004516
47    0.0      3004616
48    0.0      3004716
49   13.0      3004816
(67177, 2)
TT_S0          float64
starting_nt      int64
dtype: object
sumos ilgis: 67177
ranges ilgis: 67177
Model input - NO SCALE
       TT_S0  genes  transcripts  exons  CDSs
0        0.0      0            0      0     0
1        7.0      0            0      0     0
2        1.0      0            0      0     0
3        2.0      0            0      0     0
4        0.0      0            0      0     0
...      ...    ...          ...    ...   ...
67172    0.0      0            0      0     0
67173    0.0      0            0      0     0
67174    0.0      0            0      0     0
67175    1.0      0            0      0     0
67176    1.0      0            0      0     0

[67177 rows x 5 columns]
Model input - SCALED
       TT_S0  genes_scaled  transcripts_scaled  exons_scaled  CDSs_scaled
0        0.0             0                   0             0            0
1        7.0             0                   0             0            0
2        1.0             0                   0             0            0
3        2.0             0                   0             0            0
4        0.0             0                   0             0            0
...      ...           ...                 ...           ...          ...
67172    0.0             0                   0             0            0
67173    0.0             0                   0             0            0
67174    0.0             0                   0             0            0
67175    1.0             0                   0             0            0
67176    1.0             0                   0             0            0

[67177 rows x 5 columns]
0.17092159518882952
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]

In [6]:
print(result)

                         Length                      Length  \
count                    7301.0                      6456.0
mean                 188.590604                  177.850062
std                  174.998864                  157.257952
min                       100.0                       100.0
25%                       100.0                       100.0
50%                       100.0                       100.0
75%                       200.0                       200.0
max                      2400.0                      2000.0
ATACseq_overlap        0.697949                    0.668276
DNAseq_overlap         0.595329                    0.553813
genes_overlap          0.544833                    0.550809
percentage_open        0.141691                    0.118157
percentage_open_adj    0.204969                    0.170924
model_name                       k-means 5 features scale=1
min_open_signal            17.0                        19.0
max_open_signal           393.0                       393.0
min_closed_signal           0.0                         0.0
max_closed_signal          16.0                        18.0

                                         Length                      Length  \
count                                    7301.0                      7301.0
mean                                 188.590604                  188.590604
std                                  174.998864                  174.998864
min                                       100.0                       100.0
25%                                       100.0                       100.0
50%                                       100.0                       100.0
75%                                       200.0                       200.0
max                                      2400.0                      2400.0
ATACseq_overlap                        0.697949                    0.697949
DNAseq_overlap                         0.595329                    0.595329
genes_overlap                          0.544833                    0.544833
percentage_open                        0.141691                    0.141691
percentage_open_adj                    0.204969                    0.204969
model_name           k-means 5 features scale=2  k-means 5 features scale=4
min_open_signal                            17.0                        17.0
max_open_signal                           393.0                       393.0
min_closed_signal                           0.0                         0.0
max_closed_signal                          16.0                        16.0

                                         Length                       Length  \
count                                    7301.0                       7301.0
mean                                 188.590604                   188.590604
std                                  174.998864                   174.998864
min                                       100.0                        100.0
25%                                       100.0                        100.0
50%                                       100.0                        100.0
75%                                       200.0                        200.0
max                                      2400.0                       2400.0
ATACseq_overlap                        0.697949                     0.697949
DNAseq_overlap                         0.595329                     0.595329
genes_overlap                          0.544833                     0.544833
percentage_open                        0.141691                     0.141691
percentage_open_adj                    0.204969                     0.204969
model_name           k-means 5 features scale=8  k-means 5 features scale=16
min_open_signal                            17.0                         17.0
max_open_signal                           393.0                        393.0
min_closed_signal                           0.0                          0.0
max_closed_signal                          16.0                         16.0

                                          Length
count                                     6456.0
mean                                  177.850062
std                                   157.257952
min                                        100.0
25%                                        100.0
50%                                        100.0
75%                                        200.0
max                                       2000.0
ATACseq_overlap                         0.668276
DNAseq_overlap                          0.553813
genes_overlap                           0.550809
percentage_open                         0.118157
percentage_open_adj                     0.170924
model_name           k-means 5 features scale=32
min_open_signal                             19.0
max_open_signal                            393.0
min_closed_signal                            0.0
max_closed_signal                           18.0